// This file is auto-generated by @hey-api/openapi-ts

import type {
	Client,
	Options as ClientOptions,
	TDataShape,
} from "@hey-api/client-fetch";
import { client as _heyApiClient } from "./client.gen";
import type {
	GetAuditLogData,
	GetAuditLogError,
	GetAuditLogResponse,
	GetFeatureFlagsData,
	GetFeatureFlagsError,
	GetFeatureFlagsResponse,
	GetMeData,
	GetMeError,
	GetMeResponse,
	GetPlatformPlansData,
	GetPlatformPlansError,
	GetPlatformPlansIdData,
	GetPlatformPlansIdError,
	GetPlatformPlansIdResponse,
	GetPlatformPlansResponse,
	GetUsersData,
	GetUsersError,
	GetUsersIdData,
	GetUsersIdError,
	GetUsersIdResponse,
	GetUsersResponse,
	GetWorkspacesData,
	GetWorkspacesError,
	GetWorkspacesIdData,
	GetWorkspacesIdError,
	GetWorkspacesIdResponse,
	GetWorkspacesResponse,
	PatchPlatformPlansIdData,
	PatchPlatformPlansIdError,
	PatchPlatformPlansIdResponse,
	PatchUsersIdData,
	PatchUsersIdError,
	PatchUsersIdResponse,
	PatchWorkspacesIdData,
	PatchWorkspacesIdError,
	PatchWorkspacesIdResponse,
	PostImpersonateData,
	PostImpersonateError,
	PostImpersonateResponse,
	PostImpersonateStopData,
	PostImpersonateStopError,
	PostImpersonateStopResponse,
	PostPlatformPlansData,
	PostPlatformPlansError,
	PostPlatformPlansResponse,
	PostWorkspacesData,
	PostWorkspacesError,
	PostWorkspacesIdRestoreData,
	PostWorkspacesIdRestoreError,
	PostWorkspacesIdRestoreResponse,
	PostWorkspacesIdSuspendData,
	PostWorkspacesIdSuspendError,
	PostWorkspacesIdSuspendResponse,
	PostWorkspacesResponse,
	PutFeatureFlagsKeyData,
	PutFeatureFlagsKeyError,
	PutFeatureFlagsKeyResponse,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Identidad del superadmin autenticado
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getMe = <ThrowOnError extends boolean = false>(
	options?: Options<GetMeData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetMeResponse,
		GetMeError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/me",
		...options,
	});
};

/**
 * Listar tenants (cross-tenant)
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getWorkspaces = <ThrowOnError extends boolean = false>(
	options?: Options<GetWorkspacesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetWorkspacesResponse,
		GetWorkspacesError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/workspaces",
		...options,
	});
};

/**
 * Crear tenant
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const postWorkspaces = <ThrowOnError extends boolean = false>(
	options: Options<PostWorkspacesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostWorkspacesResponse,
		PostWorkspacesError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/workspaces",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Detalle de un tenant
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getWorkspacesId = <ThrowOnError extends boolean = false>(
	options: Options<GetWorkspacesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetWorkspacesIdResponse,
		GetWorkspacesIdError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/workspaces/{id}",
		...options,
	});
};

/**
 * Actualizar tenant
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const patchWorkspacesId = <ThrowOnError extends boolean = false>(
	options: Options<PatchWorkspacesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchWorkspacesIdResponse,
		PatchWorkspacesIdError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/workspaces/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Suspender tenant (corta acceso B2B)
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const postWorkspacesIdSuspend = <ThrowOnError extends boolean = false>(
	options: Options<PostWorkspacesIdSuspendData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostWorkspacesIdSuspendResponse,
		PostWorkspacesIdSuspendError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/workspaces/{id}/suspend",
		...options,
	});
};

/**
 * Reactivar tenant suspendido
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const postWorkspacesIdRestore = <ThrowOnError extends boolean = false>(
	options: Options<PostWorkspacesIdRestoreData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostWorkspacesIdRestoreResponse,
		PostWorkspacesIdRestoreError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/workspaces/{id}/restore",
		...options,
	});
};

/**
 * Listar usuarios cross-tenant
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getUsers = <ThrowOnError extends boolean = false>(
	options?: Options<GetUsersData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetUsersResponse,
		GetUsersError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/users",
		...options,
	});
};

/**
 * Detalle de usuario (incluye workspaces)
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getUsersId = <ThrowOnError extends boolean = false>(
	options: Options<GetUsersIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetUsersIdResponse,
		GetUsersIdError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/users/{id}",
		...options,
	});
};

/**
 * Actualizar rol global / baneo
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const patchUsersId = <ThrowOnError extends boolean = false>(
	options: Options<PatchUsersIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchUsersIdResponse,
		PatchUsersIdError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/users/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Emitir token de impersonation acotado
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const postImpersonate = <ThrowOnError extends boolean = false>(
	options: Options<PostImpersonateData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostImpersonateResponse,
		PostImpersonateError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/impersonate",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Terminar impersonation
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const postImpersonateStop = <ThrowOnError extends boolean = false>(
	options?: Options<PostImpersonateStopData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		PostImpersonateStopResponse,
		PostImpersonateStopError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/impersonate/stop",
		...options,
	});
};

/**
 * Listar planes de plataforma
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getPlatformPlans = <ThrowOnError extends boolean = false>(
	options?: Options<GetPlatformPlansData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetPlatformPlansResponse,
		GetPlatformPlansError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/platform-plans",
		...options,
	});
};

/**
 * Crear plan de plataforma
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const postPlatformPlans = <ThrowOnError extends boolean = false>(
	options: Options<PostPlatformPlansData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostPlatformPlansResponse,
		PostPlatformPlansError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/platform-plans",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Detalle de plan (límites, pricing, features)
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getPlatformPlansId = <ThrowOnError extends boolean = false>(
	options: Options<GetPlatformPlansIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetPlatformPlansIdResponse,
		GetPlatformPlansIdError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/platform-plans/{id}",
		...options,
	});
};

/**
 * Editar límites/pricing/features de un plan
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const patchPlatformPlansId = <ThrowOnError extends boolean = false>(
	options: Options<PatchPlatformPlansIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchPlatformPlansIdResponse,
		PatchPlatformPlansIdError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/platform-plans/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar feature flags
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getFeatureFlags = <ThrowOnError extends boolean = false>(
	options?: Options<GetFeatureFlagsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetFeatureFlagsResponse,
		GetFeatureFlagsError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/feature-flags",
		...options,
	});
};

/**
 * Setear un feature flag por scope
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const putFeatureFlagsKey = <ThrowOnError extends boolean = false>(
	options: Options<PutFeatureFlagsKeyData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).put<
		PutFeatureFlagsKeyResponse,
		PutFeatureFlagsKeyError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/feature-flags/{key}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Registro append-only de acciones de superadmin
 * Requiere sesión de plataforma con rol `SUPER_ADMIN`.
 */
export const getAuditLog = <ThrowOnError extends boolean = false>(
	options?: Options<GetAuditLogData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetAuditLogResponse,
		GetAuditLogError,
		ThrowOnError
	>({
		security: [
			{
				in: "cookie",
				name: "better-auth.session_token",
				type: "apiKey",
			},
		],
		url: "/audit-log",
		...options,
	});
};
