// This file is auto-generated by @hey-api/openapi-ts

export type _Error = {
	error: {
		code: string;
		message: string;
		details?: unknown;
	};
};

export type AdminMe = {
	userId: string;
	name: string;
	email: string;
	role: "SUPER_ADMIN" | "ADMIN" | "STAFF" | "VIEWER" | "MINCULTURA";
};

export type FeatureFlagScope = "global" | "plan" | "workspace";

export type Page = {
	nextCursor: string | null;
	hasMore: boolean;
};

export type AdminWorkspace = {
	id: string;
	name: string;
	slug: string;
	type: "ARTIST" | "VENUE" | "ORGANIZER";
	country: string;
	isPublished: boolean;
	suspended: boolean;
	suspendedAt: string | null;
	deletedAt: string | null;
	createdAt: string;
};

export type AdminWorkspaceCreate = {
	name: string;
	slug: string;
	type: "ARTIST" | "VENUE" | "ORGANIZER";
	country: string;
	email?: string;
};

export type AdminWorkspaceUpdate = {
	name?: string;
	slug?: string;
	type?: "ARTIST" | "VENUE" | "ORGANIZER";
	isPublished?: boolean;
};

export type AdminUserWorkspace = {
	id: string;
	name: string;
	slug: string;
	isOwner: boolean;
};

export type AdminUser = {
	id: string;
	name: string;
	email: string;
	role: "SUPER_ADMIN" | "ADMIN" | "STAFF" | "VIEWER" | "MINCULTURA";
	banned: boolean;
	bannedAt: string | null;
	homeOrganizationId: string | null;
	workspaces: Array<AdminUserWorkspace>;
	createdAt: string;
};

export type AdminUserUpdate = {
	role?: "SUPER_ADMIN" | "ADMIN" | "STAFF" | "VIEWER" | "MINCULTURA";
	banned?: boolean;
};

export type AdminImpersonate = {
	targetUserId?: string;
	workspaceId?: string;
};

export type AdminImpersonation = {
	token: string;
	expiresAt: string;
	actorUserId: string;
	targetUserId: string;
	targetOrgId: string | null;
};

export type AdminPlatformPlan = {
	id: string;
	name: string;
	slug: string;
	priceMonthly: number;
	priceYearly: number;
	priceBiannual: number | null;
	maxEvents: number | null;
	isActive: boolean;
	sortOrder: number;
	features: {
		memberships: boolean;
		content: boolean;
		fanDatabase: boolean;
		directMessages: boolean;
		streaming: boolean;
		customLanding: boolean;
		dataExport: boolean;
		seatMaps: boolean;
		customDomain: boolean;
		analytics: boolean;
	};
	createdAt: string;
};

export type AdminPlatformPlanCreate = {
	name: string;
	slug: string;
	priceMonthly: number;
	priceYearly: number;
	priceBiannual?: number | null;
	isActive: boolean;
	memberships?: boolean;
	content?: boolean;
	fanDatabase?: boolean;
	directMessages?: boolean;
	streaming?: boolean;
	customLanding?: boolean;
	dataExport?: boolean;
	seatMaps?: boolean;
	customDomain?: boolean;
	analytics?: boolean;
	maxEvents?: number | null;
};

export type AdminPlatformPlanUpdate = {
	name?: string;
	priceMonthly?: number;
	priceYearly?: number;
	priceBiannual?: number | null;
	isActive?: boolean;
	sortOrder?: number;
	memberships?: boolean;
	content?: boolean;
	fanDatabase?: boolean;
	directMessages?: boolean;
	streaming?: boolean;
	customLanding?: boolean;
	dataExport?: boolean;
	seatMaps?: boolean;
	customDomain?: boolean;
	analytics?: boolean;
	maxEvents?: number | null;
};

export type AdminFeatureFlag = {
	key: string;
	scope: FeatureFlagScope;
	scopeId: string | null;
	enabled: boolean;
	updatedBy: string | null;
	updatedAt: string;
};

export type AdminFeatureFlagSet = {
	scope: FeatureFlagScope;
	scopeId?: string;
	enabled: boolean;
};

export type AdminAuditEntry = {
	id: string;
	actorUserId: string;
	action: string;
	targetType: string;
	targetId: string;
	before: unknown | null;
	after: unknown | null;
	ipAddress: string | null;
	createdAt: string;
};

export type GetMeData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/me";
};

export type GetMeErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminMe;
	};
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetWorkspacesData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * active(default)|suspended|deleted|all
		 */
		status?: string;
		/**
		 * Búsqueda por nombre o slug
		 */
		q?: string;
		limit?: string;
		cursor?: string;
	};
	url: "/workspaces";
};

export type GetWorkspacesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetWorkspacesError = GetWorkspacesErrors[keyof GetWorkspacesErrors];

export type GetWorkspacesResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<AdminWorkspace>;
		page: Page;
	};
};

export type GetWorkspacesResponse =
	GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type PostWorkspacesData = {
	body: AdminWorkspaceCreate;
	path?: never;
	query?: never;
	url: "/workspaces";
};

export type PostWorkspacesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostWorkspacesError =
	PostWorkspacesErrors[keyof PostWorkspacesErrors];

export type PostWorkspacesResponses = {
	/**
	 * OK
	 */
	201: {
		data: AdminWorkspace;
	};
};

export type PostWorkspacesResponse =
	PostWorkspacesResponses[keyof PostWorkspacesResponses];

export type GetWorkspacesIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/workspaces/{id}";
};

export type GetWorkspacesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetWorkspacesIdError =
	GetWorkspacesIdErrors[keyof GetWorkspacesIdErrors];

export type GetWorkspacesIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminWorkspace;
	};
};

export type GetWorkspacesIdResponse =
	GetWorkspacesIdResponses[keyof GetWorkspacesIdResponses];

export type PatchWorkspacesIdData = {
	body: AdminWorkspaceUpdate;
	path: {
		id: string;
	};
	query?: never;
	url: "/workspaces/{id}";
};

export type PatchWorkspacesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchWorkspacesIdError =
	PatchWorkspacesIdErrors[keyof PatchWorkspacesIdErrors];

export type PatchWorkspacesIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminWorkspace;
	};
};

export type PatchWorkspacesIdResponse =
	PatchWorkspacesIdResponses[keyof PatchWorkspacesIdResponses];

export type PostWorkspacesIdSuspendData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/workspaces/{id}/suspend";
};

export type PostWorkspacesIdSuspendErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostWorkspacesIdSuspendError =
	PostWorkspacesIdSuspendErrors[keyof PostWorkspacesIdSuspendErrors];

export type PostWorkspacesIdSuspendResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminWorkspace;
	};
};

export type PostWorkspacesIdSuspendResponse =
	PostWorkspacesIdSuspendResponses[keyof PostWorkspacesIdSuspendResponses];

export type PostWorkspacesIdRestoreData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/workspaces/{id}/restore";
};

export type PostWorkspacesIdRestoreErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostWorkspacesIdRestoreError =
	PostWorkspacesIdRestoreErrors[keyof PostWorkspacesIdRestoreErrors];

export type PostWorkspacesIdRestoreResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminWorkspace;
	};
};

export type PostWorkspacesIdRestoreResponse =
	PostWorkspacesIdRestoreResponses[keyof PostWorkspacesIdRestoreResponses];

export type GetUsersData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Búsqueda por nombre o email
		 */
		q?: string;
		/**
		 * SUPER_ADMIN|ADMIN|STAFF|VIEWER|MINCULTURA
		 */
		role?: string;
		/**
		 * Filtra por membresía a un workspace
		 */
		workspaceId?: string;
		limit?: string;
		cursor?: string;
	};
	url: "/users";
};

export type GetUsersErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<AdminUser>;
		page: Page;
	};
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/users/{id}";
};

export type GetUsersIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetUsersIdError = GetUsersIdErrors[keyof GetUsersIdErrors];

export type GetUsersIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminUser;
	};
};

export type GetUsersIdResponse = GetUsersIdResponses[keyof GetUsersIdResponses];

export type PatchUsersIdData = {
	body: AdminUserUpdate;
	path: {
		id: string;
	};
	query?: never;
	url: "/users/{id}";
};

export type PatchUsersIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchUsersIdError = PatchUsersIdErrors[keyof PatchUsersIdErrors];

export type PatchUsersIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminUser;
	};
};

export type PatchUsersIdResponse =
	PatchUsersIdResponses[keyof PatchUsersIdResponses];

export type PostImpersonateData = {
	body: AdminImpersonate;
	path?: never;
	query?: never;
	url: "/impersonate";
};

export type PostImpersonateErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostImpersonateError =
	PostImpersonateErrors[keyof PostImpersonateErrors];

export type PostImpersonateResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminImpersonation;
	};
};

export type PostImpersonateResponse =
	PostImpersonateResponses[keyof PostImpersonateResponses];

export type PostImpersonateStopData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/impersonate/stop";
};

export type PostImpersonateStopErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostImpersonateStopError =
	PostImpersonateStopErrors[keyof PostImpersonateStopErrors];

export type PostImpersonateStopResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type PostImpersonateStopResponse =
	PostImpersonateStopResponses[keyof PostImpersonateStopResponses];

export type GetPlatformPlansData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/platform-plans";
};

export type GetPlatformPlansErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetPlatformPlansError =
	GetPlatformPlansErrors[keyof GetPlatformPlansErrors];

export type GetPlatformPlansResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<AdminPlatformPlan>;
	};
};

export type GetPlatformPlansResponse =
	GetPlatformPlansResponses[keyof GetPlatformPlansResponses];

export type PostPlatformPlansData = {
	body: AdminPlatformPlanCreate;
	path?: never;
	query?: never;
	url: "/platform-plans";
};

export type PostPlatformPlansErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostPlatformPlansError =
	PostPlatformPlansErrors[keyof PostPlatformPlansErrors];

export type PostPlatformPlansResponses = {
	/**
	 * OK
	 */
	201: {
		data: AdminPlatformPlan;
	};
};

export type PostPlatformPlansResponse =
	PostPlatformPlansResponses[keyof PostPlatformPlansResponses];

export type GetPlatformPlansIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/platform-plans/{id}";
};

export type GetPlatformPlansIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetPlatformPlansIdError =
	GetPlatformPlansIdErrors[keyof GetPlatformPlansIdErrors];

export type GetPlatformPlansIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminPlatformPlan;
	};
};

export type GetPlatformPlansIdResponse =
	GetPlatformPlansIdResponses[keyof GetPlatformPlansIdResponses];

export type PatchPlatformPlansIdData = {
	body: AdminPlatformPlanUpdate;
	path: {
		id: string;
	};
	query?: never;
	url: "/platform-plans/{id}";
};

export type PatchPlatformPlansIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchPlatformPlansIdError =
	PatchPlatformPlansIdErrors[keyof PatchPlatformPlansIdErrors];

export type PatchPlatformPlansIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminPlatformPlan;
	};
};

export type PatchPlatformPlansIdResponse =
	PatchPlatformPlansIdResponses[keyof PatchPlatformPlansIdResponses];

export type GetFeatureFlagsData = {
	body?: never;
	path?: never;
	query?: {
		key?: string;
		/**
		 * global|plan|workspace
		 */
		scope?: string;
		/**
		 * plan.slug u organization.id
		 */
		scopeId?: string;
	};
	url: "/feature-flags";
};

export type GetFeatureFlagsErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetFeatureFlagsError =
	GetFeatureFlagsErrors[keyof GetFeatureFlagsErrors];

export type GetFeatureFlagsResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<AdminFeatureFlag>;
	};
};

export type GetFeatureFlagsResponse =
	GetFeatureFlagsResponses[keyof GetFeatureFlagsResponses];

export type PutFeatureFlagsKeyData = {
	body: AdminFeatureFlagSet;
	path: {
		key: string;
	};
	query?: never;
	url: "/feature-flags/{key}";
};

export type PutFeatureFlagsKeyErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PutFeatureFlagsKeyError =
	PutFeatureFlagsKeyErrors[keyof PutFeatureFlagsKeyErrors];

export type PutFeatureFlagsKeyResponses = {
	/**
	 * OK
	 */
	200: {
		data: AdminFeatureFlag;
	};
};

export type PutFeatureFlagsKeyResponse =
	PutFeatureFlagsKeyResponses[keyof PutFeatureFlagsKeyResponses];

export type GetAuditLogData = {
	body?: never;
	path?: never;
	query?: {
		actorId?: string;
		action?: string;
		targetType?: string;
		/**
		 * ISO 8601
		 */
		from?: string;
		/**
		 * ISO 8601
		 */
		to?: string;
		limit?: string;
		cursor?: string;
	};
	url: "/audit-log";
};

export type GetAuditLogErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetAuditLogError = GetAuditLogErrors[keyof GetAuditLogErrors];

export type GetAuditLogResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<AdminAuditEntry>;
		page: Page;
	};
};

export type GetAuditLogResponse =
	GetAuditLogResponses[keyof GetAuditLogResponses];

export type ClientOptions = {
	baseUrl: "https://admin.appfreeticket.com/api/admin" | (string & {});
};
