// This file is auto-generated by @hey-api/openapi-ts

import type {
	Client,
	Options as ClientOptions,
	TDataShape,
} from "@hey-api/client-fetch";
import { client as _heyApiClient } from "./client.gen";
import type {
	GetEventsData,
	GetEventsError,
	GetEventsResponse,
	GetEventsSlugAvailabilityData,
	GetEventsSlugAvailabilityError,
	GetEventsSlugAvailabilityResponse,
	GetEventsSlugData,
	GetEventsSlugError,
	GetEventsSlugResponse,
	GetOrdersIdData,
	GetOrdersIdError,
	GetOrdersIdResponse,
	PostOrdersData,
	PostOrdersError,
	PostOrdersResponse,
	PostTicketsCodeResendData,
	PostTicketsCodeResendError,
	PostTicketsCodeResendResponse,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Reenviar el correo con el ticket/QR al comprador (anónimo)
 * Público (sin auth). Reenvía el email con el QR al correo registrado en la compra. Body opcional `{ email }` que debe coincidir con el del comprador. Devuelve el correo enmascarado, nunca el completo. Rate limit por código (1/min).
 */
export const postTicketsCodeResend = <ThrowOnError extends boolean = false>(
	options: Options<PostTicketsCodeResendData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostTicketsCodeResendResponse,
		PostTicketsCodeResendError,
		ThrowOnError
	>({
		url: "/tickets/{code}/resend",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Catálogo público de eventos (descubrimiento B2C)
 * Público (sin auth). Lista eventos PUBLISHED con al menos una función futura. Filtros: `q` (texto), `city`, `from`/`to` (ISO 8601), `page`, `pageSize` (≤50), `sort` (date_asc | price_asc | price_desc). Devuelve resumen con precio 'desde' y próxima fecha. Cache-friendly, sin datos personales.
 */
export const getEvents = <ThrowOnError extends boolean = false>(
	options?: Options<GetEventsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetEventsResponse,
		GetEventsError,
		ThrowOnError
	>({
		url: "/events",
		...options,
	});
};

/**
 * Detalle público de un evento por slug
 * Público (sin auth). Ficha del evento PUBLISHED: descripción, fechas (con venue y ciudad) y precio 'desde'. Para el stock en vivo por tipo de ticket, usar `/events/{slug}/availability`.
 */
export const getEventsSlug = <ThrowOnError extends boolean = false>(
	options: Options<GetEventsSlugData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetEventsSlugResponse,
		GetEventsSlugError,
		ThrowOnError
	>({
		url: "/events/{slug}",
		...options,
	});
};

/**
 * Disponibilidad en vivo por fecha y tipo de ticket
 * Público (sin auth). Stock en vivo (capacidad - vendido - reservado) por función y tipo de ticket, solo funciones futuras. Consultar antes de crear una orden. No cachear agresivo: el stock cambia.
 */
export const getEventsSlugAvailability = <ThrowOnError extends boolean = false>(
	options: Options<GetEventsSlugAvailabilityData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetEventsSlugAvailabilityResponse,
		GetEventsSlugAvailabilityError,
		ThrowOnError
	>({
		url: "/events/{slug}/availability",
		...options,
	});
};

/**
 * Crear una orden B2C y obtener el link de pago (Mercado Pago)
 * Público (sin auth). Crea una venta PENDING + reserva de stock (30 min) y devuelve la `checkoutUrl` de Mercado Pago a la que mandar al comprador. El agente NUNCA procesa el pago. Solo admisión general (no numerado / no members-only) de eventos PUBLISHED con venta abierta y de un mismo organizador. Cupo protegido con transacción Serializable. Consultar el estado con `GET /orders/{id}`.
 */
export const postOrders = <ThrowOnError extends boolean = false>(
	options: Options<PostOrdersData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostOrdersResponse,
		PostOrdersError,
		ThrowOnError
	>({
		url: "/orders",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Estado de una orden B2C (y tickets al pagar)
 * Público (sin auth). Estado de la orden: `pending | paid | expired | cancelled`. Al pagar (`paid`) incluye los códigos de ticket emitidos; el QR/entrada llega por email. El id es un cuid no enumerable; no expone datos del comprador.
 */
export const getOrdersId = <ThrowOnError extends boolean = false>(
	options: Options<GetOrdersIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetOrdersIdResponse,
		GetOrdersIdError,
		ThrowOnError
	>({
		url: "/orders/{id}",
		...options,
	});
};
