// This file is auto-generated by @hey-api/openapi-ts

export type _Error = {
	error: {
		code: string;
		message: string;
		details?: unknown;
	};
};

export type ResendTicketRequest = {
	email?: string;
};

export type ResendTicketResult = {
	sent: true;
	maskedEmail: string;
};

export type PublicEventSummary = {
	slug: string;
	name: string;
	description: string | null;
	coverImageUrl: string | null;
	city: string | null;
	nextDate: string | null;
	priceFrom: number | null;
	currency: string;
};

export type PublicTicketType = {
	id: string;
	name: string;
	description: string | null;
	price: number;
	currency: string;
	maxPerOrder: number;
	available: number;
	soldOut: boolean;
};

export type PublicEventDate = {
	id: string;
	label: string | null;
	startsAt: string;
	endsAt: string | null;
	timezone: string;
	venueName: string | null;
	city: string | null;
};

export type PublicEventDetail = {
	slug: string;
	name: string;
	description: string | null;
	coverImageUrl: string | null;
	city: string | null;
	nextDate: string | null;
	priceFrom: number | null;
	currency: string;
	dates: Array<PublicEventDate>;
};

export type PublicAvailability = {
	slug: string;
	dates: Array<{
		id: string;
		label: string | null;
		startsAt: string;
		endsAt: string | null;
		timezone: string;
		venueName: string | null;
		city: string | null;
		ticketTypes: Array<PublicTicketType>;
	}>;
};

export type CreateOrderRequest = {
	buyerEmail: string;
	buyerName: string;
	buyerPhone?: string;
	items: Array<{
		ticketTypeId: string;
		quantity: number;
	}>;
};

export type OrderCreated = {
	orderId: string;
	reference: string;
	status: "pending" | "paid" | "expired" | "cancelled";
	total: number;
	currency: string;
	checkoutUrl: string;
};

export type OrderTicket = {
	ticketCode: string;
	ticketTypeName: string;
};

export type OrderStatus = {
	orderId: string;
	reference: string;
	status: "pending" | "paid" | "expired" | "cancelled";
	total: number;
	currency: string;
	tickets: Array<OrderTicket>;
};

export type PostTicketsCodeResendData = {
	body: ResendTicketRequest;
	path: {
		code: string;
	};
	query?: never;
	url: "/tickets/{code}/resend";
};

export type PostTicketsCodeResendErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostTicketsCodeResendError =
	PostTicketsCodeResendErrors[keyof PostTicketsCodeResendErrors];

export type PostTicketsCodeResendResponses = {
	/**
	 * OK
	 */
	200: {
		data: ResendTicketResult;
	};
};

export type PostTicketsCodeResendResponse =
	PostTicketsCodeResendResponses[keyof PostTicketsCodeResendResponses];

export type GetEventsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Búsqueda por nombre/descripción
		 */
		q?: string;
		/**
		 * Filtra por ciudad del venue
		 */
		city?: string;
		/**
		 * Funciones desde (ISO 8601)
		 */
		from?: string;
		/**
		 * Funciones hasta (ISO 8601)
		 */
		to?: string;
		/**
		 * Página (default 1)
		 */
		page?: string;
		/**
		 * Tamaño de página (default 20, máx 50)
		 */
		pageSize?: string;
		/**
		 * date_asc | price_asc | price_desc
		 */
		sort?: string;
	};
	url: "/events";
};

export type GetEventsErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetEventsError = GetEventsErrors[keyof GetEventsErrors];

export type GetEventsResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<PublicEventSummary>;
	};
};

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses];

export type GetEventsSlugData = {
	body?: never;
	path: {
		slug: string;
	};
	query?: never;
	url: "/events/{slug}";
};

export type GetEventsSlugErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetEventsSlugError = GetEventsSlugErrors[keyof GetEventsSlugErrors];

export type GetEventsSlugResponses = {
	/**
	 * OK
	 */
	200: {
		data: PublicEventDetail;
	};
};

export type GetEventsSlugResponse =
	GetEventsSlugResponses[keyof GetEventsSlugResponses];

export type GetEventsSlugAvailabilityData = {
	body?: never;
	path: {
		slug: string;
	};
	query?: never;
	url: "/events/{slug}/availability";
};

export type GetEventsSlugAvailabilityErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetEventsSlugAvailabilityError =
	GetEventsSlugAvailabilityErrors[keyof GetEventsSlugAvailabilityErrors];

export type GetEventsSlugAvailabilityResponses = {
	/**
	 * OK
	 */
	200: {
		data: PublicAvailability;
	};
};

export type GetEventsSlugAvailabilityResponse =
	GetEventsSlugAvailabilityResponses[keyof GetEventsSlugAvailabilityResponses];

export type PostOrdersData = {
	body: CreateOrderRequest;
	path?: never;
	query?: never;
	url: "/orders";
};

export type PostOrdersErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostOrdersError = PostOrdersErrors[keyof PostOrdersErrors];

export type PostOrdersResponses = {
	/**
	 * OK
	 */
	201: {
		data: OrderCreated;
	};
};

export type PostOrdersResponse = PostOrdersResponses[keyof PostOrdersResponses];

export type GetOrdersIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/orders/{id}";
};

export type GetOrdersIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetOrdersIdError = GetOrdersIdErrors[keyof GetOrdersIdErrors];

export type GetOrdersIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: OrderStatus;
	};
};

export type GetOrdersIdResponse =
	GetOrdersIdResponses[keyof GetOrdersIdResponses];

export type ClientOptions = {
	baseUrl: "https://admin.appfreeticket.com/api/public" | (string & {});
};
