// This file is auto-generated by @hey-api/openapi-ts

import type {
	Client,
	Options as ClientOptions,
	TDataShape,
} from "@hey-api/client-fetch";
import { client as _heyApiClient } from "./client.gen";
import type {
	DeleteDiscountsIdData,
	DeleteDiscountsIdError,
	DeleteDiscountsIdResponse,
	DeleteEventsIdData,
	DeleteEventsIdDatesDateIdData,
	DeleteEventsIdDatesDateIdError,
	DeleteEventsIdDatesDateIdResponse,
	DeleteEventsIdError,
	DeleteEventsIdResponse,
	DeleteMembershipPlansIdData,
	DeleteMembershipPlansIdError,
	DeleteMembershipPlansIdResponse,
	DeleteTicketTypesIdData,
	DeleteTicketTypesIdError,
	DeleteTicketTypesIdResponse,
	DeleteVenuesIdData,
	DeleteVenuesIdError,
	DeleteVenuesIdResponse,
	DeleteWebhooksIdData,
	DeleteWebhooksIdError,
	DeleteWebhooksIdResponse,
	GetDiscountsData,
	GetDiscountsError,
	GetDiscountsResponse,
	GetEventsData,
	GetEventsError,
	GetEventsIdData,
	GetEventsIdDatesData,
	GetEventsIdDatesError,
	GetEventsIdDatesResponse,
	GetEventsIdError,
	GetEventsIdResponse,
	GetEventsResponse,
	GetMeData,
	GetMeError,
	GetMembershipPlansData,
	GetMembershipPlansError,
	GetMembershipPlansIdData,
	GetMembershipPlansIdError,
	GetMembershipPlansIdResponse,
	GetMembershipPlansIdSubscribersData,
	GetMembershipPlansIdSubscribersError,
	GetMembershipPlansIdSubscribersResponse,
	GetMembershipPlansResponse,
	GetMeResponse,
	GetReportsByEventData,
	GetReportsByEventError,
	GetReportsByEventResponse,
	GetReportsExportsAttendeesData,
	GetReportsExportsAttendeesError,
	GetReportsExportsAttendeesResponse,
	GetReportsExportsBuyersData,
	GetReportsExportsBuyersError,
	GetReportsExportsBuyersResponse,
	GetReportsExportsReconciliationData,
	GetReportsExportsReconciliationError,
	GetReportsExportsReconciliationResponse,
	GetReportsExportsSubscribersData,
	GetReportsExportsSubscribersError,
	GetReportsExportsSubscribersResponse,
	GetReportsInventoryData,
	GetReportsInventoryError,
	GetReportsInventoryResponse,
	GetReportsReconciliationData,
	GetReportsReconciliationError,
	GetReportsReconciliationResponse,
	GetReportsSummaryData,
	GetReportsSummaryError,
	GetReportsSummaryResponse,
	GetReportsTimeseriesData,
	GetReportsTimeseriesError,
	GetReportsTimeseriesResponse,
	GetSalesData,
	GetSalesError,
	GetSalesIdData,
	GetSalesIdError,
	GetSalesIdResponse,
	GetSalesIdTicketsData,
	GetSalesIdTicketsError,
	GetSalesIdTicketsResponse,
	GetSalesResponse,
	GetStaffData,
	GetStaffError,
	GetStaffResponse,
	GetTicketsTicketCodeAccessData,
	GetTicketsTicketCodeAccessError,
	GetTicketsTicketCodeAccessResponse,
	GetTicketTypesData,
	GetTicketTypesError,
	GetTicketTypesIdData,
	GetTicketTypesIdError,
	GetTicketTypesIdResponse,
	GetTicketTypesResponse,
	GetVenuesData,
	GetVenuesError,
	GetVenuesIdData,
	GetVenuesIdError,
	GetVenuesIdResponse,
	GetVenuesResponse,
	GetWebhooksData,
	GetWebhooksError,
	GetWebhooksResponse,
	PatchDiscountsIdData,
	PatchDiscountsIdError,
	PatchDiscountsIdResponse,
	PatchEventsIdData,
	PatchEventsIdDatesDateIdData,
	PatchEventsIdDatesDateIdError,
	PatchEventsIdDatesDateIdResponse,
	PatchEventsIdError,
	PatchEventsIdResponse,
	PatchMembershipPlansIdData,
	PatchMembershipPlansIdError,
	PatchMembershipPlansIdResponse,
	PatchStaffIdRoleData,
	PatchStaffIdRoleError,
	PatchStaffIdRoleResponse,
	PatchTicketTypesIdData,
	PatchTicketTypesIdError,
	PatchTicketTypesIdResponse,
	PatchVenuesIdData,
	PatchVenuesIdError,
	PatchVenuesIdResponse,
	PostAuthDeviceCodeData,
	PostAuthDeviceCodeError,
	PostAuthDeviceCodeResponse,
	PostAuthDeviceTokenData,
	PostAuthDeviceTokenError,
	PostAuthDeviceTokenResponse,
	PostDiscountsData,
	PostDiscountsError,
	PostDiscountsResponse,
	PostEventsData,
	PostEventsError,
	PostEventsIdDatesData,
	PostEventsIdDatesError,
	PostEventsIdDatesResponse,
	PostEventsIdPublishData,
	PostEventsIdPublishError,
	PostEventsIdPublishResponse,
	PostEventsResponse,
	PostMembershipPlansData,
	PostMembershipPlansError,
	PostMembershipPlansResponse,
	PostSalesData,
	PostSalesError,
	PostSalesIdCancelData,
	PostSalesIdCancelError,
	PostSalesIdCancelResponse,
	PostSalesIdRefundData,
	PostSalesIdRefundError,
	PostSalesIdRefundResponse,
	PostSalesResponse,
	PostStaffData,
	PostStaffError,
	PostStaffResponse,
	PostSubscriptionsIdCancelData,
	PostSubscriptionsIdCancelError,
	PostSubscriptionsIdCancelResponse,
	PostTicketsTicketCodeCheckinData,
	PostTicketsTicketCodeCheckinError,
	PostTicketsTicketCodeCheckinResponse,
	PostTicketsTicketCodeResendData,
	PostTicketsTicketCodeResendError,
	PostTicketsTicketCodeResendResponse,
	PostTicketTypesData,
	PostTicketTypesError,
	PostTicketTypesResponse,
	PostVenuesData,
	PostVenuesError,
	PostVenuesResponse,
	PostWebhooksData,
	PostWebhooksError,
	PostWebhooksResponse,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Inicia el Device Authorization Grant (RFC 8628)
 * Endpoint público (sin auth): bootstrap de credenciales del Device Authorization Grant (RFC 8628).
 */
export const postAuthDeviceCode = <ThrowOnError extends boolean = false>(
	options?: Options<PostAuthDeviceCodeData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		PostAuthDeviceCodeResponse,
		PostAuthDeviceCodeError,
		ThrowOnError
	>({
		url: "/auth/device/code",
		...options,
	});
};

/**
 * Poll del CLI: canjea el device_code por una API key al aprobar
 * Endpoint público (sin auth): bootstrap de credenciales del Device Authorization Grant (RFC 8628).
 */
export const postAuthDeviceToken = <ThrowOnError extends boolean = false>(
	options: Options<PostAuthDeviceTokenData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostAuthDeviceTokenResponse,
		PostAuthDeviceTokenError,
		ThrowOnError
	>({
		url: "/auth/device/token",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Usuario autenticado, rol y workspaces accesibles
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getMe = <ThrowOnError extends boolean = false>(
	options?: Options<GetMeData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetMeResponse,
		GetMeError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/me",
		...options,
	});
};

/**
 * Listar eventos del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getEvents = <ThrowOnError extends boolean = false>(
	options?: Options<GetEventsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetEventsResponse,
		GetEventsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events",
		...options,
	});
};

/**
 * Crear evento (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postEvents = <ThrowOnError extends boolean = false>(
	options: Options<PostEventsData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostEventsResponse,
		PostEventsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) evento (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteEventsId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteEventsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteEventsIdResponse,
		DeleteEventsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events/{id}",
		...options,
	});
};

/**
 * Obtener un evento
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getEventsId = <ThrowOnError extends boolean = false>(
	options: Options<GetEventsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetEventsIdResponse,
		GetEventsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events/{id}",
		...options,
	});
};

/**
 * Actualizar evento (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchEventsId = <ThrowOnError extends boolean = false>(
	options: Options<PatchEventsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchEventsIdResponse,
		PatchEventsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Publicar evento (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postEventsIdPublish = <ThrowOnError extends boolean = false>(
	options: Options<PostEventsIdPublishData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostEventsIdPublishResponse,
		PostEventsIdPublishError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events/{id}/publish",
		...options,
	});
};

/**
 * Listar fechas de un evento
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getEventsIdDates = <ThrowOnError extends boolean = false>(
	options: Options<GetEventsIdDatesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetEventsIdDatesResponse,
		GetEventsIdDatesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events/{id}/dates",
		...options,
	});
};

/**
 * Agregar fecha a un evento (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postEventsIdDates = <ThrowOnError extends boolean = false>(
	options: Options<PostEventsIdDatesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostEventsIdDatesResponse,
		PostEventsIdDatesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events/{id}/dates",
		...options,
	});
};

/**
 * Eliminar fecha (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteEventsIdDatesDateId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteEventsIdDatesDateIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteEventsIdDatesDateIdResponse,
		DeleteEventsIdDatesDateIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events/{id}/dates/{dateId}",
		...options,
	});
};

/**
 * Actualizar fecha (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchEventsIdDatesDateId = <ThrowOnError extends boolean = false>(
	options: Options<PatchEventsIdDatesDateIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchEventsIdDatesDateIdResponse,
		PatchEventsIdDatesDateIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/events/{id}/dates/{dateId}",
		...options,
	});
};

/**
 * Listar tipos de ticket del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getTicketTypes = <ThrowOnError extends boolean = false>(
	options?: Options<GetTicketTypesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetTicketTypesResponse,
		GetTicketTypesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/ticket-types",
		...options,
	});
};

/**
 * Crear tipo de ticket (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postTicketTypes = <ThrowOnError extends boolean = false>(
	options: Options<PostTicketTypesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostTicketTypesResponse,
		PostTicketTypesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/ticket-types",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) tipo de ticket (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteTicketTypesId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteTicketTypesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteTicketTypesIdResponse,
		DeleteTicketTypesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/ticket-types/{id}",
		...options,
	});
};

/**
 * Obtener un tipo de ticket
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getTicketTypesId = <ThrowOnError extends boolean = false>(
	options: Options<GetTicketTypesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetTicketTypesIdResponse,
		GetTicketTypesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/ticket-types/{id}",
		...options,
	});
};

/**
 * Actualizar tipo de ticket (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchTicketTypesId = <ThrowOnError extends boolean = false>(
	options: Options<PatchTicketTypesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchTicketTypesIdResponse,
		PatchTicketTypesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/ticket-types/{id}",
		...options,
	});
};

/**
 * Listar ventas del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getSales = <ThrowOnError extends boolean = false>(
	options?: Options<GetSalesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetSalesResponse,
		GetSalesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/sales",
		...options,
	});
};

/**
 * Crear una venta/orden (cortesías y ventas programáticas)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postSales = <ThrowOnError extends boolean = false>(
	options: Options<PostSalesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostSalesResponse,
		PostSalesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/sales",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Detalle de una venta con sus ítems
 * Rol mínimo: `STAFF`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getSalesId = <ThrowOnError extends boolean = false>(
	options: Options<GetSalesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetSalesIdResponse,
		GetSalesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/sales/{id}",
		...options,
	});
};

/**
 * Cancelar una venta (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postSalesIdCancel = <ThrowOnError extends boolean = false>(
	options: Options<PostSalesIdCancelData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostSalesIdCancelResponse,
		PostSalesIdCancelError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/sales/{id}/cancel",
		...options,
	});
};

/**
 * Reembolsar una venta (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postSalesIdRefund = <ThrowOnError extends boolean = false>(
	options: Options<PostSalesIdRefundData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostSalesIdRefundResponse,
		PostSalesIdRefundError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/sales/{id}/refund",
		...options,
	});
};

/**
 * Listar planes de membresía del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getMembershipPlans = <ThrowOnError extends boolean = false>(
	options?: Options<GetMembershipPlansData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetMembershipPlansResponse,
		GetMembershipPlansError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/membership-plans",
		...options,
	});
};

/**
 * Crear plan de membresía (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postMembershipPlans = <ThrowOnError extends boolean = false>(
	options: Options<PostMembershipPlansData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostMembershipPlansResponse,
		PostMembershipPlansError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/membership-plans",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) plan (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteMembershipPlansId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteMembershipPlansIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteMembershipPlansIdResponse,
		DeleteMembershipPlansIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/membership-plans/{id}",
		...options,
	});
};

/**
 * Obtener un plan de membresía
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getMembershipPlansId = <ThrowOnError extends boolean = false>(
	options: Options<GetMembershipPlansIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetMembershipPlansIdResponse,
		GetMembershipPlansIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/membership-plans/{id}",
		...options,
	});
};

/**
 * Actualizar plan (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchMembershipPlansId = <ThrowOnError extends boolean = false>(
	options: Options<PatchMembershipPlansIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchMembershipPlansIdResponse,
		PatchMembershipPlansIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/membership-plans/{id}",
		...options,
	});
};

/**
 * Listar venues del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getVenues = <ThrowOnError extends boolean = false>(
	options?: Options<GetVenuesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetVenuesResponse,
		GetVenuesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/venues",
		...options,
	});
};

/**
 * Crear venue (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postVenues = <ThrowOnError extends boolean = false>(
	options: Options<PostVenuesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostVenuesResponse,
		PostVenuesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/venues",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) venue (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteVenuesId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteVenuesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteVenuesIdResponse,
		DeleteVenuesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/venues/{id}",
		...options,
	});
};

/**
 * Obtener un venue
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getVenuesId = <ThrowOnError extends boolean = false>(
	options: Options<GetVenuesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetVenuesIdResponse,
		GetVenuesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/venues/{id}",
		...options,
	});
};

/**
 * Actualizar venue (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchVenuesId = <ThrowOnError extends boolean = false>(
	options: Options<PatchVenuesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchVenuesIdResponse,
		PatchVenuesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/venues/{id}",
		...options,
	});
};

/**
 * Listar staff con acceso al workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getStaff = <ThrowOnError extends boolean = false>(
	options?: Options<GetStaffData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetStaffResponse,
		GetStaffError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/staff",
		...options,
	});
};

/**
 * Crear usuario staff (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postStaff = <ThrowOnError extends boolean = false>(
	options: Options<PostStaffData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostStaffResponse,
		PostStaffError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/staff",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Cambiar rol de un usuario staff (fase 2)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchStaffIdRole = <ThrowOnError extends boolean = false>(
	options: Options<PatchStaffIdRoleData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchStaffIdRoleResponse,
		PatchStaffIdRoleError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/staff/{id}/role",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * KPIs del workspace (revenue, tickets, ventas, membresías)
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsSummary = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsSummaryData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsSummaryResponse,
		GetReportsSummaryError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/summary",
		...options,
	});
};

/**
 * Inventario agregado por evento/fecha/tipo (capacidad, vendidos, disponibles)
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsInventory = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsInventoryData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsInventoryResponse,
		GetReportsInventoryError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/inventory",
		...options,
	});
};

/**
 * Conciliación financiera CFO (MP ↔ venta ↔ factura Siigo)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsReconciliation = <ThrowOnError extends boolean = false>(
	options: Options<GetReportsReconciliationData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetReportsReconciliationResponse,
		GetReportsReconciliationError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/reconciliation",
		...options,
	});
};

/**
 * Export CSV de la conciliación financiera CFO
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsExportsReconciliation = <
	ThrowOnError extends boolean = false,
>(
	options: Options<GetReportsExportsReconciliationData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetReportsExportsReconciliationResponse,
		GetReportsExportsReconciliationError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/exports/reconciliation",
		...options,
	});
};

/**
 * Export de asistentes por ticket con filtros (máx 5000)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsExportsAttendees = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<GetReportsExportsAttendeesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsExportsAttendeesResponse,
		GetReportsExportsAttendeesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/exports/attendees",
		...options,
	});
};

/**
 * Export de compradores con filtros (máx 5000)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsExportsBuyers = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsExportsBuyersData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsExportsBuyersResponse,
		GetReportsExportsBuyersError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/exports/buyers",
		...options,
	});
};

/**
 * Export de suscriptores (máx 5000)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsExportsSubscribers = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<GetReportsExportsSubscribersData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsExportsSubscribersResponse,
		GetReportsExportsSubscribersError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/exports/subscribers",
		...options,
	});
};

/**
 * KPIs de venta por evento del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsByEvent = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsByEventData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsByEventResponse,
		GetReportsByEventError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/by-event",
		...options,
	});
};

/**
 * Serie temporal de ventas CONFIRMED por bucket (day|week|month)
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsTimeseries = <ThrowOnError extends boolean = false>(
	options: Options<GetReportsTimeseriesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetReportsTimeseriesResponse,
		GetReportsTimeseriesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/reports/timeseries",
		...options,
	});
};

/**
 * Listar cupones de descuento del workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getDiscounts = <ThrowOnError extends boolean = false>(
	options?: Options<GetDiscountsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetDiscountsResponse,
		GetDiscountsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/discounts",
		...options,
	});
};

/**
 * Crear cupón de descuento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postDiscounts = <ThrowOnError extends boolean = false>(
	options: Options<PostDiscountsData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostDiscountsResponse,
		PostDiscountsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/discounts",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) cupón de descuento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteDiscountsId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteDiscountsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteDiscountsIdResponse,
		DeleteDiscountsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/discounts/{id}",
		...options,
	});
};

/**
 * Actualizar cupón de descuento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchDiscountsId = <ThrowOnError extends boolean = false>(
	options: Options<PatchDiscountsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchDiscountsIdResponse,
		PatchDiscountsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/discounts/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar webhooks del workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getWebhooks = <ThrowOnError extends boolean = false>(
	options?: Options<GetWebhooksData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetWebhooksResponse,
		GetWebhooksError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/webhooks",
		...options,
	});
};

/**
 * Crear webhook (devuelve el signingSecret una única vez)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postWebhooks = <ThrowOnError extends boolean = false>(
	options: Options<PostWebhooksData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostWebhooksResponse,
		PostWebhooksError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/webhooks",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar un webhook del workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteWebhooksId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteWebhooksIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteWebhooksIdResponse,
		DeleteWebhooksIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/webhooks/{id}",
		...options,
	});
};

/**
 * Listar suscriptores de un plan de membresía
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getMembershipPlansIdSubscribers = <
	ThrowOnError extends boolean = false,
>(
	options: Options<GetMembershipPlansIdSubscribersData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetMembershipPlansIdSubscribersResponse,
		GetMembershipPlansIdSubscribersError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/membership-plans/{id}/subscribers",
		...options,
	});
};

/**
 * Cancelar una suscripción de membresía
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postSubscriptionsIdCancel = <ThrowOnError extends boolean = false>(
	options: Options<PostSubscriptionsIdCancelData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostSubscriptionsIdCancelResponse,
		PostSubscriptionsIdCancelError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/subscriptions/{id}/cancel",
		...options,
	});
};

/**
 * Tickets individuales de una venta
 * Rol mínimo: `STAFF`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getSalesIdTickets = <ThrowOnError extends boolean = false>(
	options: Options<GetSalesIdTicketsData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetSalesIdTicketsResponse,
		GetSalesIdTicketsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/sales/{id}/tickets",
		...options,
	});
};

/**
 * Registrar el ingreso (check-in) de un ticket en puerta
 * Rol mínimo: `STAFF`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postTicketsTicketCodeCheckin = <
	ThrowOnError extends boolean = false,
>(
	options: Options<PostTicketsTicketCodeCheckinData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostTicketsTicketCodeCheckinResponse,
		PostTicketsTicketCodeCheckinError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/tickets/{ticketCode}/checkin",
		...options,
	});
};

/**
 * Consultar la validez de un ticket sin consumirlo
 * Rol mínimo: `STAFF`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getTicketsTicketCodeAccess = <
	ThrowOnError extends boolean = false,
>(
	options: Options<GetTicketsTicketCodeAccessData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetTicketsTicketCodeAccessResponse,
		GetTicketsTicketCodeAccessError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/tickets/{ticketCode}/access",
		...options,
	});
};

/**
 * Reenviar el correo de confirmación con el ticket
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postTicketsTicketCodeResend = <
	ThrowOnError extends boolean = false,
>(
	options: Options<PostTicketsTicketCodeResendData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostTicketsTicketCodeResendResponse,
		PostTicketsTicketCodeResendError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
		],
		url: "/tickets/{ticketCode}/resend",
		...options,
	});
};
