// This file is auto-generated by @hey-api/openapi-ts

import type {
	Client,
	Options as ClientOptions,
	TDataShape,
} from "@hey-api/client-fetch";
import { client as _heyApiClient } from "./client.gen";
import type {
	DeleteApiKeysIdData,
	DeleteApiKeysIdError,
	DeleteApiKeysIdResponse,
	DeleteDiscountsIdData,
	DeleteDiscountsIdError,
	DeleteDiscountsIdResponse,
	DeleteEventsIdData,
	DeleteEventsIdDatesDateIdData,
	DeleteEventsIdDatesDateIdError,
	DeleteEventsIdDatesDateIdResponse,
	DeleteEventsIdError,
	DeleteEventsIdResponse,
	DeleteMembershipPlansIdData,
	DeleteMembershipPlansIdError,
	DeleteMembershipPlansIdResponse,
	DeleteTicketTypesIdData,
	DeleteTicketTypesIdError,
	DeleteTicketTypesIdResponse,
	DeleteVenuesIdData,
	DeleteVenuesIdError,
	DeleteVenuesIdResponse,
	DeleteWebhooksIdData,
	DeleteWebhooksIdError,
	DeleteWebhooksIdResponse,
	GetApiKeysData,
	GetApiKeysError,
	GetApiKeysResponse,
	GetContentLivesData,
	GetContentLivesError,
	GetContentLivesIdData,
	GetContentLivesIdError,
	GetContentLivesIdResponse,
	GetContentLivesResponse,
	GetContentPostsData,
	GetContentPostsError,
	GetContentPostsResponse,
	GetContentVideosData,
	GetContentVideosError,
	GetContentVideosResponse,
	GetCustomerMeData,
	GetCustomerMeError,
	GetCustomerMembershipData,
	GetCustomerMembershipError,
	GetCustomerMembershipResponse,
	GetCustomerMeResponse,
	GetCustomerProfileData,
	GetCustomerProfileError,
	GetCustomerProfileResponse,
	GetCustomerTicketsData,
	GetCustomerTicketsError,
	GetCustomerTicketsIdData,
	GetCustomerTicketsIdError,
	GetCustomerTicketsIdResponse,
	GetCustomerTicketsResponse,
	GetDiscountsData,
	GetDiscountsError,
	GetDiscountsResponse,
	GetEventsData,
	GetEventsError,
	GetEventsIdData,
	GetEventsIdDatesData,
	GetEventsIdDatesError,
	GetEventsIdDatesResponse,
	GetEventsIdError,
	GetEventsIdResponse,
	GetEventsResponse,
	GetMeData,
	GetMeError,
	GetMembershipPlansData,
	GetMembershipPlansError,
	GetMembershipPlansIdData,
	GetMembershipPlansIdError,
	GetMembershipPlansIdResponse,
	GetMembershipPlansIdSubscribersData,
	GetMembershipPlansIdSubscribersError,
	GetMembershipPlansIdSubscribersResponse,
	GetMembershipPlansResponse,
	GetMeResponse,
	GetReportsByEventData,
	GetReportsByEventError,
	GetReportsByEventResponse,
	GetReportsExportsAttendeesData,
	GetReportsExportsAttendeesError,
	GetReportsExportsAttendeesResponse,
	GetReportsExportsBuyersData,
	GetReportsExportsBuyersError,
	GetReportsExportsBuyersResponse,
	GetReportsExportsReconciliationData,
	GetReportsExportsReconciliationError,
	GetReportsExportsReconciliationResponse,
	GetReportsExportsSubscribersData,
	GetReportsExportsSubscribersError,
	GetReportsExportsSubscribersResponse,
	GetReportsFinancialsData,
	GetReportsFinancialsError,
	GetReportsFinancialsResponse,
	GetReportsInventoryData,
	GetReportsInventoryError,
	GetReportsInventoryResponse,
	GetReportsReconciliationData,
	GetReportsReconciliationError,
	GetReportsReconciliationResponse,
	GetReportsSummaryData,
	GetReportsSummaryError,
	GetReportsSummaryResponse,
	GetReportsTimeseriesData,
	GetReportsTimeseriesError,
	GetReportsTimeseriesResponse,
	GetSalesData,
	GetSalesError,
	GetSalesIdData,
	GetSalesIdError,
	GetSalesIdResponse,
	GetSalesIdTicketsData,
	GetSalesIdTicketsError,
	GetSalesIdTicketsResponse,
	GetSalesResponse,
	GetSettlementsData,
	GetSettlementsError,
	GetSettlementsIdDocumentData,
	GetSettlementsIdDocumentError,
	GetSettlementsIdProofsFileNameData,
	GetSettlementsIdProofsFileNameError,
	GetSettlementsResponse,
	GetStaffData,
	GetStaffError,
	GetStaffResponse,
	GetTicketsTicketCodeAccessData,
	GetTicketsTicketCodeAccessError,
	GetTicketsTicketCodeAccessResponse,
	GetTicketTypesData,
	GetTicketTypesError,
	GetTicketTypesIdData,
	GetTicketTypesIdError,
	GetTicketTypesIdResponse,
	GetTicketTypesResponse,
	GetVenuesData,
	GetVenuesError,
	GetVenuesIdData,
	GetVenuesIdError,
	GetVenuesIdResponse,
	GetVenuesResponse,
	GetWebhooksData,
	GetWebhooksError,
	GetWebhooksResponse,
	PatchCustomerProfileData,
	PatchCustomerProfileError,
	PatchCustomerProfileResponse,
	PatchDiscountsIdData,
	PatchDiscountsIdError,
	PatchDiscountsIdResponse,
	PatchEventsIdData,
	PatchEventsIdDatesDateIdData,
	PatchEventsIdDatesDateIdError,
	PatchEventsIdDatesDateIdResponse,
	PatchEventsIdError,
	PatchEventsIdResponse,
	PatchMembershipPlansIdData,
	PatchMembershipPlansIdError,
	PatchMembershipPlansIdResponse,
	PatchStaffIdRoleData,
	PatchStaffIdRoleError,
	PatchStaffIdRoleResponse,
	PatchTicketTypesIdData,
	PatchTicketTypesIdError,
	PatchTicketTypesIdResponse,
	PatchVenuesIdData,
	PatchVenuesIdError,
	PatchVenuesIdResponse,
	PostApiCustomerAuthEnterpriseExchangeData,
	PostApiCustomerAuthEnterpriseExchangeResponse,
	PostApiKeysData,
	PostApiKeysError,
	PostApiKeysResponse,
	PostAuthDeviceCodeData,
	PostAuthDeviceCodeError,
	PostAuthDeviceCodeResponse,
	PostAuthDeviceTokenData,
	PostAuthDeviceTokenError,
	PostAuthDeviceTokenResponse,
	PostContentPlaybackTokenData,
	PostContentPlaybackTokenError,
	PostContentPlaybackTokenResponse,
	PostCustomerLogoutData,
	PostCustomerLogoutError,
	PostCustomerLogoutResponse,
	PostCustomerSubscriptionsCancelData,
	PostCustomerSubscriptionsCancelError,
	PostCustomerSubscriptionsCancelResponse,
	PostCustomerSubscriptionsData,
	PostCustomerSubscriptionsError,
	PostCustomerSubscriptionsResponse,
	PostCustomerTicketsIdCancelData,
	PostCustomerTicketsIdCancelError,
	PostCustomerTicketsIdCancelResponse,
	PostDiscountsData,
	PostDiscountsError,
	PostDiscountsResponse,
	PostEventsData,
	PostEventsError,
	PostEventsIdDatesData,
	PostEventsIdDatesError,
	PostEventsIdDatesResponse,
	PostEventsIdPublishData,
	PostEventsIdPublishError,
	PostEventsIdPublishResponse,
	PostEventsResponse,
	PostMembershipPlansData,
	PostMembershipPlansError,
	PostMembershipPlansResponse,
	PostSalesData,
	PostSalesError,
	PostSalesIdCancelData,
	PostSalesIdCancelError,
	PostSalesIdCancelResponse,
	PostSalesIdRefundData,
	PostSalesIdRefundError,
	PostSalesIdRefundResponse,
	PostSalesResponse,
	PostStaffData,
	PostStaffError,
	PostStaffResponse,
	PostSubscriptionsIdCancelData,
	PostSubscriptionsIdCancelError,
	PostSubscriptionsIdCancelResponse,
	PostTicketsTicketCodeCheckinData,
	PostTicketsTicketCodeCheckinError,
	PostTicketsTicketCodeCheckinResponse,
	PostTicketsTicketCodeResendData,
	PostTicketsTicketCodeResendError,
	PostTicketsTicketCodeResendResponse,
	PostTicketTypesData,
	PostTicketTypesError,
	PostTicketTypesResponse,
	PostVenuesData,
	PostVenuesError,
	PostVenuesResponse,
	PostWebhooksData,
	PostWebhooksError,
	PostWebhooksResponse,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Listar fechas de un evento
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getEventsIdDates = <ThrowOnError extends boolean = false>(
	options: Options<GetEventsIdDatesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetEventsIdDatesResponse,
		GetEventsIdDatesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events/{id}/dates",
		...options,
	});
};

/**
 * Agregar fecha a un evento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postEventsIdDates = <ThrowOnError extends boolean = false>(
	options: Options<PostEventsIdDatesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostEventsIdDatesResponse,
		PostEventsIdDatesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events/{id}/dates",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Inicia el Device Authorization Grant (RFC 8628)
 * Endpoint público (sin auth): bootstrap de credenciales del Device Authorization Grant (RFC 8628).
 */
export const postAuthDeviceCode = <ThrowOnError extends boolean = false>(
	options?: Options<PostAuthDeviceCodeData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		PostAuthDeviceCodeResponse,
		PostAuthDeviceCodeError,
		ThrowOnError
	>({
		url: "/auth/device/code",
		...options,
	});
};

/**
 * Poll del CLI: canjea el device_code por una API key al aprobar
 * Endpoint público (sin auth): bootstrap de credenciales del Device Authorization Grant (RFC 8628).
 */
export const postAuthDeviceToken = <ThrowOnError extends boolean = false>(
	options: Options<PostAuthDeviceTokenData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostAuthDeviceTokenResponse,
		PostAuthDeviceTokenError,
		ThrowOnError
	>({
		url: "/auth/device/token",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Usuario autenticado, rol y workspaces accesibles
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getMe = <ThrowOnError extends boolean = false>(
	options?: Options<GetMeData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetMeResponse,
		GetMeError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/me",
		...options,
	});
};

/**
 * Listar eventos del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`. Cada evento embebe `nextDate` (su función más próxima, o null), para no requerir `/events/{id}/dates` por evento al renderizar un catálogo.
 */
export const getEvents = <ThrowOnError extends boolean = false>(
	options?: Options<GetEventsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetEventsResponse,
		GetEventsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events",
		...options,
	});
};

/**
 * Crear evento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postEvents = <ThrowOnError extends boolean = false>(
	options: Options<PostEventsData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostEventsResponse,
		PostEventsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) evento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteEventsId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteEventsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteEventsIdResponse,
		DeleteEventsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events/{id}",
		...options,
	});
};

/**
 * Obtener un evento
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getEventsId = <ThrowOnError extends boolean = false>(
	options: Options<GetEventsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetEventsIdResponse,
		GetEventsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events/{id}",
		...options,
	});
};

/**
 * Actualizar evento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchEventsId = <ThrowOnError extends boolean = false>(
	options: Options<PatchEventsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchEventsIdResponse,
		PatchEventsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Publicar evento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postEventsIdPublish = <ThrowOnError extends boolean = false>(
	options: Options<PostEventsIdPublishData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostEventsIdPublishResponse,
		PostEventsIdPublishError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events/{id}/publish",
		...options,
	});
};

/**
 * Eliminar fecha
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteEventsIdDatesDateId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteEventsIdDatesDateIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteEventsIdDatesDateIdResponse,
		DeleteEventsIdDatesDateIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events/{id}/dates/{dateId}",
		...options,
	});
};

/**
 * Actualizar fecha
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchEventsIdDatesDateId = <ThrowOnError extends boolean = false>(
	options: Options<PatchEventsIdDatesDateIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchEventsIdDatesDateIdResponse,
		PatchEventsIdDatesDateIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/events/{id}/dates/{dateId}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar tipos de ticket del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getTicketTypes = <ThrowOnError extends boolean = false>(
	options?: Options<GetTicketTypesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetTicketTypesResponse,
		GetTicketTypesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/ticket-types",
		...options,
	});
};

/**
 * Crear tipo de ticket
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postTicketTypes = <ThrowOnError extends boolean = false>(
	options: Options<PostTicketTypesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostTicketTypesResponse,
		PostTicketTypesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/ticket-types",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) tipo de ticket
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteTicketTypesId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteTicketTypesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteTicketTypesIdResponse,
		DeleteTicketTypesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/ticket-types/{id}",
		...options,
	});
};

/**
 * Obtener un tipo de ticket
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getTicketTypesId = <ThrowOnError extends boolean = false>(
	options: Options<GetTicketTypesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetTicketTypesIdResponse,
		GetTicketTypesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/ticket-types/{id}",
		...options,
	});
};

/**
 * Actualizar tipo de ticket
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchTicketTypesId = <ThrowOnError extends boolean = false>(
	options: Options<PatchTicketTypesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchTicketTypesIdResponse,
		PatchTicketTypesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/ticket-types/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar ventas del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getSales = <ThrowOnError extends boolean = false>(
	options?: Options<GetSalesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetSalesResponse,
		GetSalesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/sales",
		...options,
	});
};

/**
 * Crear una venta/orden (cortesías y ventas programáticas)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postSales = <ThrowOnError extends boolean = false>(
	options: Options<PostSalesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostSalesResponse,
		PostSalesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/sales",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Detalle de una venta con sus ítems
 * Rol mínimo: `STAFF`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getSalesId = <ThrowOnError extends boolean = false>(
	options: Options<GetSalesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetSalesIdResponse,
		GetSalesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/sales/{id}",
		...options,
	});
};

/**
 * Cancelar una venta (bloqueada si el cobro sigue abierto)
 * Marca la venta como CANCELLED, libera su cupo y suelta las sillas numeradas asociadas. IMPORTANTE: una venta PENDING cobrada con Bold tiene un enlace de pago que puede seguir vivo — el API de Bold nunca marca sus enlaces como vencidos —, así que cancelarla podría dejar al comprador pagado y sin entrada. Antes de cancelar se relee el estado real del cobro: si Bold lo reporta aprobado, responde 409 SALE_PAID_AT_GATEWAY y NO se cancela en ningún caso (esa venta se confirma o se reembolsa). Si el cobro sigue abierto o el estado no se puede leer, responde 409 OPEN_PAYMENT_CONFIRMATION_REQUIRED: verifica en el panel de Bold y repite la llamada con {"acknowledge_open_payment": true} para asumir el riesgo de forma explícita. Las ventas de otras pasarelas y las que no tienen un pago iniciado se cancelan sin ese paso.
 */
export const postSalesIdCancel = <ThrowOnError extends boolean = false>(
	options: Options<PostSalesIdCancelData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostSalesIdCancelResponse,
		PostSalesIdCancelError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/sales/{id}/cancel",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Reembolsar una venta (el movimiento de fondos depende de la pasarela)
 * Marca la venta como REFUNDED y libera las sillas numeradas asociadas. IMPORTANTE: que el dinero vuelva al comprador depende de la pasarela de pago y del medio usado. Solo las ventas cobradas con Wompi y TARJETA se anulan de verdad contra la pasarela de pago antes de marcarse. En cualquier otro caso este endpoint NO dispara el reembolso real: el dinero NO se devuelve automáticamente y un 200 confirma únicamente el cambio de estado contable. Esos reembolsos deben gestionarse por separado en el panel de la pasarela de pago. Los medios de Wompi sin devolución por API (PSE, Nequi, transferencia Bancolombia) responden 409: hay que devolver la plata en el panel de Wompi y repetir la llamada con {"acknowledge_manual": true} para reflejar el estado contable. Un 502 significa que la pasarela rechazó la anulación y la venta sigue CONFIRMED.
 */
export const postSalesIdRefund = <ThrowOnError extends boolean = false>(
	options: Options<PostSalesIdRefundData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostSalesIdRefundResponse,
		PostSalesIdRefundError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/sales/{id}/refund",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar planes de membresía del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getMembershipPlans = <ThrowOnError extends boolean = false>(
	options?: Options<GetMembershipPlansData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetMembershipPlansResponse,
		GetMembershipPlansError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/membership-plans",
		...options,
	});
};

/**
 * Crear plan de membresía
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postMembershipPlans = <ThrowOnError extends boolean = false>(
	options: Options<PostMembershipPlansData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostMembershipPlansResponse,
		PostMembershipPlansError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/membership-plans",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) plan
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteMembershipPlansId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteMembershipPlansIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteMembershipPlansIdResponse,
		DeleteMembershipPlansIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/membership-plans/{id}",
		...options,
	});
};

/**
 * Obtener un plan de membresía
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getMembershipPlansId = <ThrowOnError extends boolean = false>(
	options: Options<GetMembershipPlansIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetMembershipPlansIdResponse,
		GetMembershipPlansIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/membership-plans/{id}",
		...options,
	});
};

/**
 * Actualizar plan
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchMembershipPlansId = <ThrowOnError extends boolean = false>(
	options: Options<PatchMembershipPlansIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchMembershipPlansIdResponse,
		PatchMembershipPlansIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/membership-plans/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar venues del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getVenues = <ThrowOnError extends boolean = false>(
	options?: Options<GetVenuesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetVenuesResponse,
		GetVenuesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/venues",
		...options,
	});
};

/**
 * Crear venue
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postVenues = <ThrowOnError extends boolean = false>(
	options: Options<PostVenuesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostVenuesResponse,
		PostVenuesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/venues",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) venue
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteVenuesId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteVenuesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteVenuesIdResponse,
		DeleteVenuesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/venues/{id}",
		...options,
	});
};

/**
 * Obtener un venue
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getVenuesId = <ThrowOnError extends boolean = false>(
	options: Options<GetVenuesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetVenuesIdResponse,
		GetVenuesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/venues/{id}",
		...options,
	});
};

/**
 * Actualizar venue
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchVenuesId = <ThrowOnError extends boolean = false>(
	options: Options<PatchVenuesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchVenuesIdResponse,
		PatchVenuesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/venues/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar staff con acceso al workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`. Con `?workspaceIds=` la paginación por cursor sigue siendo por usuario: `limit` cuenta personas, no filas.
 */
export const getStaff = <ThrowOnError extends boolean = false>(
	options?: Options<GetStaffData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetStaffResponse,
		GetStaffError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/staff",
		...options,
	});
};

/**
 * Crear usuario staff en el workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postStaff = <ThrowOnError extends boolean = false>(
	options: Options<PostStaffData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostStaffResponse,
		PostStaffError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/staff",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Cambiar rol de un usuario staff
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchStaffIdRole = <ThrowOnError extends boolean = false>(
	options: Options<PatchStaffIdRoleData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchStaffIdRoleResponse,
		PatchStaffIdRoleError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/staff/{id}/role",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * KPIs del workspace (revenue, tickets, ventas, membresías)
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsSummary = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsSummaryData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsSummaryResponse,
		GetReportsSummaryError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/summary",
		...options,
	});
};

/**
 * Inventario agregado por evento/fecha/tipo (capacidad, vendidos, disponibles)
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsInventory = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsInventoryData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsInventoryResponse,
		GetReportsInventoryError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/inventory",
		...options,
	});
};

/**
 * Conciliación financiera CFO (MP ↔ venta ↔ factura Siigo)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsReconciliation = <ThrowOnError extends boolean = false>(
	options: Options<GetReportsReconciliationData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetReportsReconciliationResponse,
		GetReportsReconciliationError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/reconciliation",
		...options,
	});
};

/**
 * Export CSV de la conciliación financiera CFO
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsExportsReconciliation = <
	ThrowOnError extends boolean = false,
>(
	options: Options<GetReportsExportsReconciliationData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetReportsExportsReconciliationResponse,
		GetReportsExportsReconciliationError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/exports/reconciliation",
		...options,
	});
};

/**
 * Export de asistentes por ticket con filtros (máx 5000)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsExportsAttendees = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<GetReportsExportsAttendeesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsExportsAttendeesResponse,
		GetReportsExportsAttendeesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/exports/attendees",
		...options,
	});
};

/**
 * Export de compradores con filtros (máx 5000)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsExportsBuyers = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsExportsBuyersData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsExportsBuyersResponse,
		GetReportsExportsBuyersError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/exports/buyers",
		...options,
	});
};

/**
 * Export de suscriptores (máx 5000)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsExportsSubscribers = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<GetReportsExportsSubscribersData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsExportsSubscribersResponse,
		GetReportsExportsSubscribersError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/exports/subscribers",
		...options,
	});
};

/**
 * KPIs de venta por evento del workspace
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsByEvent = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsByEventData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsByEventResponse,
		GetReportsByEventError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/by-event",
		...options,
	});
};

/**
 * Serie temporal de ventas CONFIRMED por bucket (day|week|month)
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getReportsTimeseries = <ThrowOnError extends boolean = false>(
	options: Options<GetReportsTimeseriesData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetReportsTimeseriesResponse,
		GetReportsTimeseriesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/timeseries",
		...options,
	});
};

/**
 * Estado financiero por función: bruto, costos y neto a liquidar
 * Una fila por función (event_date) con el desglose financiero de sus ventas confirmadas — bruto cobrado, cargo de plataforma + IVA, valor facial, comisión de la pasarela (real en MercadoPago, estimada por tasa en Wompi o Bold), 4x1000 y neto a liquidar — más el estado de la liquidación asociada. Si wompiSalesWithoutRate > 0, la comisión de ventas de Wompi o Bold no se pudo estimar y el neto está inflado.
 */
export const getReportsFinancials = <ThrowOnError extends boolean = false>(
	options?: Options<GetReportsFinancialsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetReportsFinancialsResponse,
		GetReportsFinancialsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/reports/financials",
		...options,
	});
};

/**
 * Liquidaciones del workspace (pagos al organizador)
 * Lista las liquidaciones visibles para la organización (SENT, AWAITING_PAYMENT, PAID) con su id estándar, monto, evento/función y comprobantes. Los archivos se bajan con `GET /settlements/{id}/document` (PDF) y `GET /settlements/{id}/proofs/{fileName}` (comprobantes de la transferencia).
 */
export const getSettlements = <ThrowOnError extends boolean = false>(
	options?: Options<GetSettlementsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetSettlementsResponse,
		GetSettlementsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/settlements",
		...options,
	});
};

/**
 * Descarga el PDF de una liquidación
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`. Los archivos viven en un bucket privado, así que la respuesta es un **302** hacia una URL firmada de 5 minutos (hay que seguir la redirección; el `storage_path` nunca se expone). Solo liquidaciones visibles para la organización (SENT, AWAITING_PAYMENT, PAID) y dentro del `event_scope` de la key.
 */
export const getSettlementsIdDocument = <ThrowOnError extends boolean = false>(
	options: Options<GetSettlementsIdDocumentData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		unknown,
		GetSettlementsIdDocumentError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/settlements/{id}/document",
		...options,
	});
};

/**
 * Descarga un comprobante de pago de una liquidación
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`. `fileName` es el mismo valor que devuelve `paymentProofs[].fileName` en `GET /settlements` (URL-encoded). Igual que `/document`, responde **302** hacia una URL firmada de 5 minutos del bucket privado.
 */
export const getSettlementsIdProofsFileName = <
	ThrowOnError extends boolean = false,
>(
	options: Options<GetSettlementsIdProofsFileNameData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		unknown,
		GetSettlementsIdProofsFileNameError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/settlements/{id}/proofs/{fileName}",
		...options,
	});
};

/**
 * Listar cupones de descuento del workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getDiscounts = <ThrowOnError extends boolean = false>(
	options?: Options<GetDiscountsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetDiscountsResponse,
		GetDiscountsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/discounts",
		...options,
	});
};

/**
 * Crear cupón de descuento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postDiscounts = <ThrowOnError extends boolean = false>(
	options: Options<PostDiscountsData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostDiscountsResponse,
		PostDiscountsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/discounts",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar (soft) cupón de descuento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteDiscountsId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteDiscountsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteDiscountsIdResponse,
		DeleteDiscountsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/discounts/{id}",
		...options,
	});
};

/**
 * Actualizar cupón de descuento
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const patchDiscountsId = <ThrowOnError extends boolean = false>(
	options: Options<PatchDiscountsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchDiscountsIdResponse,
		PatchDiscountsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/discounts/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar webhooks del workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getWebhooks = <ThrowOnError extends boolean = false>(
	options?: Options<GetWebhooksData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetWebhooksResponse,
		GetWebhooksError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/webhooks",
		...options,
	});
};

/**
 * Crear webhook (devuelve el signingSecret una única vez)
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postWebhooks = <ThrowOnError extends boolean = false>(
	options: Options<PostWebhooksData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostWebhooksResponse,
		PostWebhooksError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/webhooks",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Eliminar un webhook del workspace
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteWebhooksId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteWebhooksIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteWebhooksIdResponse,
		DeleteWebhooksIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/webhooks/{id}",
		...options,
	});
};

/**
 * Listar suscriptores de un plan de membresía
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getMembershipPlansIdSubscribers = <
	ThrowOnError extends boolean = false,
>(
	options: Options<GetMembershipPlansIdSubscribersData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetMembershipPlansIdSubscribersResponse,
		GetMembershipPlansIdSubscribersError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/membership-plans/{id}/subscribers",
		...options,
	});
};

/**
 * Cancelar una suscripción de membresía
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postSubscriptionsIdCancel = <ThrowOnError extends boolean = false>(
	options: Options<PostSubscriptionsIdCancelData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostSubscriptionsIdCancelResponse,
		PostSubscriptionsIdCancelError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/subscriptions/{id}/cancel",
		...options,
	});
};

/**
 * Tickets individuales de una venta
 * Rol mínimo: `STAFF`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getSalesIdTickets = <ThrowOnError extends boolean = false>(
	options: Options<GetSalesIdTicketsData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetSalesIdTicketsResponse,
		GetSalesIdTicketsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/sales/{id}/tickets",
		...options,
	});
};

/**
 * Registrar el ingreso (check-in) de un ticket en puerta
 * Rol mínimo: `STAFF`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postTicketsTicketCodeCheckin = <
	ThrowOnError extends boolean = false,
>(
	options: Options<PostTicketsTicketCodeCheckinData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostTicketsTicketCodeCheckinResponse,
		PostTicketsTicketCodeCheckinError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/tickets/{ticketCode}/checkin",
		...options,
	});
};

/**
 * Consultar la validez de un ticket sin consumirlo
 * Rol mínimo: `STAFF`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getTicketsTicketCodeAccess = <
	ThrowOnError extends boolean = false,
>(
	options: Options<GetTicketsTicketCodeAccessData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetTicketsTicketCodeAccessResponse,
		GetTicketsTicketCodeAccessError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/tickets/{ticketCode}/access",
		...options,
	});
};

/**
 * Listar mis API keys
 * Lista las API keys del usuario autenticado (nunca el hash ni el secreto en claro).
 */
export const getApiKeys = <ThrowOnError extends boolean = false>(
	options?: Options<GetApiKeysData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetApiKeysResponse,
		GetApiKeysError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/api-keys",
		...options,
	});
};

/**
 * Mintear una API key (devuelve el plano una única vez)
 * Crea una API key de servicio para el usuario autenticado. scope="read" (default) solo permite GET/HEAD; scope="write" habilita mutaciones según el rol del usuario. El secreto en claro solo aparece en esta respuesta.
 */
export const postApiKeys = <ThrowOnError extends boolean = false>(
	options: Options<PostApiKeysData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostApiKeysResponse,
		PostApiKeysError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/api-keys",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Revocar una de mis API keys
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const deleteApiKeysId = <ThrowOnError extends boolean = false>(
	options: Options<DeleteApiKeysIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).delete<
		DeleteApiKeysIdResponse,
		DeleteApiKeysIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/api-keys/{id}",
		...options,
	});
};

/**
 * Identidad del comprador autenticado (SSO headless)
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session` con el session_token obtenido en el canje del SSO headless.
 */
export const getCustomerMe = <ThrowOnError extends boolean = false>(
	options?: Options<GetCustomerMeData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetCustomerMeResponse,
		GetCustomerMeError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/me",
		...options,
	});
};

/**
 * Entradas del comprador en el alcance de la key (SSO headless)
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`. Devuelve solo ventas CONFIRMED, matcheadas por cuenta del comprador o correo de compra, de eventos que el workspace pineado a la key puede leer: los propios Y aquellos donde figura como artista vinculado.
 */
export const getCustomerTickets = <ThrowOnError extends boolean = false>(
	options?: Options<GetCustomerTicketsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetCustomerTicketsResponse,
		GetCustomerTicketsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/tickets",
		...options,
	});
};

/**
 * Detalle de una entrada del comprador (deep link)
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`. `{id}` acepta el id de la venta o su `reference`. Devuelve 404 si la entrada no es del comprador de la sesión o cae fuera del alcance del workspace de la key.
 */
export const getCustomerTicketsId = <ThrowOnError extends boolean = false>(
	options: Options<GetCustomerTicketsIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetCustomerTicketsIdResponse,
		GetCustomerTicketsIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/tickets/{id}",
		...options,
	});
};

/**
 * Cancelar la propia compra (solo si aún no fue pagada)
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`. Solo cancela ventas PENDING (libera cupo y sillas). Una venta CONFIRMED responde 409 con código `REFUND_REQUIRED`: el reembolso lo gestiona el organizador. `{id}` acepta el id de la venta o su `reference`.
 */
export const postCustomerTicketsIdCancel = <
	ThrowOnError extends boolean = false,
>(
	options: Options<PostCustomerTicketsIdCancelData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostCustomerTicketsIdCancelResponse,
		PostCustomerTicketsIdCancelError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/tickets/{id}/cancel",
		...options,
	});
};

/**
 * Cerrar la sesión de comprador (SSO headless)
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`. Borra la sesión del comprador: el `session_token` deja de servir en el acto. Idempotente.
 */
export const postCustomerLogout = <ThrowOnError extends boolean = false>(
	options?: Options<PostCustomerLogoutData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		PostCustomerLogoutResponse,
		PostCustomerLogoutError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/logout",
		...options,
	});
};

/**
 * Canjear el one-time token del SSO headless por un session token
 * Server-to-server: exige una API key de servicio enterprise (Bearer o x-api-key). Canjea el one-time token entregado por /api/customer-auth/enterprise-return (single-use, TTL 60s) por el session token del comprador. Body plano, sin envoltura { data }.
 */
export const postApiCustomerAuthEnterpriseExchange = <
	ThrowOnError extends boolean = false,
>(
	options: Options<PostApiCustomerAuthEnterpriseExchangeData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostApiCustomerAuthEnterpriseExchangeResponse,
		unknown,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/api/customer-auth/enterprise-exchange",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Estado de membresía del comprador en el workspace de la key
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`. `active` es true solo con membresía ACTIVE y vigente. Si no hay ninguna vigente, `membership` trae la más reciente (vencida, cancelada o pendiente de pago) para que la landing elija el CTA; `null` = nunca fue miembro de este workspace.
 */
export const getCustomerMembership = <ThrowOnError extends boolean = false>(
	options?: Options<GetCustomerMembershipData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetCustomerMembershipResponse,
		GetCustomerMembershipError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/membership",
		...options,
	});
};

/**
 * Iniciar el alta de una membresía (devuelve la URL de pago)
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`. Valida que el plan pertenezca al workspace de la key y que el comprador pueda adquirirlo, y devuelve la URL del checkout de membresía del host canónico (el cobro lo cierra la plataforma). Al volver, releer `GET /customer/membership`.
 */
export const postCustomerSubscriptions = <ThrowOnError extends boolean = false>(
	options: Options<PostCustomerSubscriptionsData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostCustomerSubscriptionsResponse,
		PostCustomerSubscriptionsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/subscriptions",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Cancelar la propia membresía (SSO headless)
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`. La membresía se resuelve por la sesión del comprador y el workspace de la key (no se acepta ningún id). Cancela primero el cobro recurrente en el proveedor y después marca la membresía como CANCELLED. Idempotente.
 */
export const postCustomerSubscriptionsCancel = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<PostCustomerSubscriptionsCancelData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).post<
		PostCustomerSubscriptionsCancelResponse,
		PostCustomerSubscriptionsCancelError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/subscriptions/cancel",
		...options,
	});
};

/**
 * Perfil del comprador (nombre y teléfono)
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`.
 */
export const getCustomerProfile = <ThrowOnError extends boolean = false>(
	options?: Options<GetCustomerProfileData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetCustomerProfileResponse,
		GetCustomerProfileError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/profile",
		...options,
	});
};

/**
 * Editar el perfil del comprador
 * Requiere API key de servicio enterprise Y el header `X-Customer-Session`. Edita solo al comprador de la sesión: nombre y teléfono. El correo no se edita (es la identidad de la cuenta). Campos ausentes no se tocan.
 */
export const patchCustomerProfile = <ThrowOnError extends boolean = false>(
	options: Options<PatchCustomerProfileData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).patch<
		PatchCustomerProfileResponse,
		PatchCustomerProfileError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/customer/profile",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Listar los videos publicados de la organización
 * Solo videos publicados y con procesamiento terminado (READY) del workspace activo. No incluye el playback id: para reproducir hay que pedir un token en `POST /content/playback-token`.
 */
export const getContentVideos = <ThrowOnError extends boolean = false>(
	options?: Options<GetContentVideosData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetContentVideosResponse,
		GetContentVideosError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/content/videos",
		...options,
	});
};

/**
 * Listar el feed de comunidad de la organización
 * Publicaciones del workspace activo, de la más reciente a la más vieja, sin borradas ni programadas a futuro. Un post con `locked: true` llega redactado (`content`, `imageUrl`, `videoId`, `eventId` y `link` en null, `commentsCount` en 0): es contenido reservado a miembros y la key no representa a un comprador con membresía vigente. No incluye `likes_count` (solo visible para el dueño del workspace) ni el autor interno de la publicación.
 */
export const getContentPosts = <ThrowOnError extends boolean = false>(
	options?: Options<GetContentPostsData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetContentPostsResponse,
		GetContentPostsError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/content/posts",
		...options,
	});
};

/**
 * Listar las transmisiones de la organización
 * Transmisiones del workspace activo, de la más reciente a la más vieja. `status: ACTIVE` es la que está al aire. No incluye la clave RTMP ni los playback ids.
 */
export const getContentLives = <ThrowOnError extends boolean = false>(
	options?: Options<GetContentLivesData, ThrowOnError>,
) => {
	return (options?.client ?? _heyApiClient).get<
		GetContentLivesResponse,
		GetContentLivesError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/content/lives",
		...options,
	});
};

/**
 * Estado de una transmisión
 * Rol mínimo: `VIEWER`. Workspace activo vía header `X-Workspace-Id`.
 */
export const getContentLivesId = <ThrowOnError extends boolean = false>(
	options: Options<GetContentLivesIdData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).get<
		GetContentLivesIdResponse,
		GetContentLivesIdError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/content/lives/{id}",
		...options,
	});
};

/**
 * Token firmado para reproducir un video o una transmisión
 * Requiere API key de servicio enterprise. El contenido `memberOnly` exige además el header `X-Customer-Session` de un comprador con membresía vigente en la organización de la key (si no, 403 `MEMBERSHIP_REQUIRED`). El contenido de otra organización responde 404. Tokens de vida corta: 30 minutos en vivo, 1 hora en video.
 */
export const postContentPlaybackToken = <ThrowOnError extends boolean = false>(
	options: Options<PostContentPlaybackTokenData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostContentPlaybackTokenResponse,
		PostContentPlaybackTokenError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/content/playback-token",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Reenviar el correo de confirmación con el ticket
 * Rol mínimo: `ADMIN`. Workspace activo vía header `X-Workspace-Id`.
 */
export const postTicketsTicketCodeResend = <
	ThrowOnError extends boolean = false,
>(
	options: Options<PostTicketsTicketCodeResendData, ThrowOnError>,
) => {
	return (options.client ?? _heyApiClient).post<
		PostTicketsTicketCodeResendResponse,
		PostTicketsTicketCodeResendError,
		ThrowOnError
	>({
		security: [
			{
				name: "Authorization",
				type: "apiKey",
			},
			{
				name: "x-api-key",
				type: "apiKey",
			},
		],
		url: "/tickets/{ticketCode}/resend",
		...options,
	});
};
