// This file is auto-generated by @hey-api/openapi-ts

export type _Error = {
	error: {
		code: string;
		message: string;
		details?: unknown;
	};
};

export type Page = {
	nextCursor: string | null;
	hasMore: boolean;
};

export type Workspace = {
	id: string;
	name: string;
	slug: string;
};

export type Me = {
	userId: string;
	name: string;
	email: string;
	role: "SUPER_ADMIN" | "ADMIN" | "STAFF" | "VIEWER" | "MINCULTURA";
	activeWorkspaceId: string;
	workspaces: Array<Workspace>;
};

export type DeviceCodeResponse = {
	device_code: string;
	user_code: string;
	verification_uri: string;
	verification_uri_complete: string;
	expires_in: number;
	interval: number;
};

export type DeviceTokenRequest = {
	device_code: string;
	grant_type?: "urn:ietf:params:oauth:grant-type:device_code";
};

export type DeviceTokenResponse = {
	access_token: string;
	token_type: "Bearer";
	user: {
		id: string;
		email: string;
		role: "SUPER_ADMIN" | "ADMIN" | "STAFF" | "VIEWER" | "MINCULTURA";
	};
	workspaces: Array<Workspace>;
};

export type DeviceTokenError = {
	error:
		| "authorization_pending"
		| "slow_down"
		| "expired_token"
		| "access_denied"
		| "invalid_request";
};

export type Event = {
	id: string;
	name: string;
	slug: string;
	description: string | null;
	status: "DRAFT" | "PUBLISHED" | "SOLD_OUT" | "CANCELLED" | "COMPLETED";
	coverImageUrl: string | null;
	organizationId: string;
	venueId: string | null;
	createdAt: string;
	updatedAt: string;
};

export type EventDate = {
	id: string;
	eventId: string;
	label: string | null;
	startsAt: string;
	endsAt: string | null;
	doorsOpenAt: string | null;
	timezone: string;
	venueId: string | null;
	status: "DRAFT" | "PUBLISHED" | "SOLD_OUT" | "CANCELLED" | "COMPLETED";
	streamType: string;
	createdAt: string;
};

export type EventCreate = {
	name: string;
	slug: string;
	description?: string;
	venueId?: string | null;
	dates: Array<{
		startsAt: string;
		endsAt?: string | null;
		timezone: string;
	}>;
};

export type EventUpdate = {
	name?: string;
	description?: string | null;
	venueId?: string | null;
	coverImageUrl?: string | null;
};

export type TicketType = {
	id: string;
	eventDateId: string;
	name: string;
	description: string | null;
	price: number;
	currency: string;
	capacity: number;
	maxPerOrder: number;
	saleStartsAt: string | null;
	saleEndsAt: string | null;
	isVisible: boolean;
	organizerAbsorbsFee: boolean;
	createdAt: string;
};

export type TicketTypeCreate = {
	eventDateId: string;
	name: string;
	description?: string;
	price: number;
	currency: string;
	capacity: number;
	maxPerOrder: number;
	isVisible: boolean;
	organizerAbsorbsFee: boolean;
};

export type SaleItem = {
	id: string;
	ticketTypeId: string;
	quantity: number;
	unitPrice: number;
	subtotal: number;
	ticketCode: string;
	checkedInAt: string | null;
};

export type Sale = {
	id: string;
	reference: string;
	status: "PENDING" | "CONFIRMED" | "ABANDONED" | "CANCELLED" | "REFUNDED";
	channel: string;
	subtotal: number;
	discountAmount: number;
	serviceFee: number;
	iva: number;
	total: number;
	currency: string;
	buyerName: string;
	buyerEmail: string;
	buyerPhone: string | null;
	organizationId: string | null;
	confirmedAt: string | null;
	createdAt: string;
};

export type SaleDetail = {
	id: string;
	reference: string;
	status: "PENDING" | "CONFIRMED" | "ABANDONED" | "CANCELLED" | "REFUNDED";
	channel: string;
	subtotal: number;
	discountAmount: number;
	serviceFee: number;
	iva: number;
	total: number;
	currency: string;
	buyerName: string;
	buyerEmail: string;
	buyerPhone: string | null;
	organizationId: string | null;
	confirmedAt: string | null;
	createdAt: string;
	items: Array<SaleItem>;
};

export type MembershipPlan = {
	id: string;
	organizationId: string | null;
	name: string;
	description: string | null;
	price: number;
	currency: string;
	billingCycle: "MONTHLY" | "QUARTERLY" | "ANNUAL" | "LIFETIME";
	benefits: {
		presale: boolean;
		freeTicket: boolean;
		discount: boolean;
		exclusiveContent: boolean;
		merch: boolean;
	};
	isActive: boolean;
	sortOrder: number;
	createdAt: string;
};

export type MembershipPlanCreate = {
	name: string;
	description?: string;
	price: number;
	currency: string;
	billingCycle: "MONTHLY" | "QUARTERLY" | "ANNUAL" | "LIFETIME";
	benefitPresale: boolean;
	benefitFreeTicket: boolean;
	benefitDiscount: boolean;
	benefitExclusiveContent: boolean;
	benefitMerch: boolean;
	isActive: boolean;
};

export type Venue = {
	id: string;
	name: string;
	slug: string;
	address: string;
	city: string;
	country: string;
	latitude: number | null;
	longitude: number | null;
	capacity: number | null;
	googlePlaceId: string | null;
	portalVisible: boolean;
	organizationId: string | null;
	createdAt: string;
};

export type VenueCreate = {
	name: string;
	address: string;
	city: string;
	country: string;
	capacity?: number;
	latitude?: number;
	longitude?: number;
};

export type StaffUser = {
	id: string;
	name: string;
	email: string;
	role: "SUPER_ADMIN" | "ADMIN" | "STAFF" | "VIEWER" | "MINCULTURA";
	organizationId: string | null;
	createdAt: string;
};

export type StaffCreate = {
	name: string;
	email: string;
};

export type RoleUpdate = {
	role: "SUPER_ADMIN" | "ADMIN" | "STAFF" | "VIEWER" | "MINCULTURA";
};

export type ReportSummary = {
	period: string;
	currency: string;
	revenue: number;
	ticketsSold: number;
	salesCount: number;
	activeMemberships: number;
};

export type MatchStatus =
	| "OK"
	| "MISSING_INVOICE"
	| "MISSING_CUFE"
	| "AMOUNT_MISMATCH"
	| "MISSING_PAYMENT";

export type InventoryRow = {
	eventId: string;
	eventName: string;
	eventStatus: "DRAFT" | "PUBLISHED" | "SOLD_OUT" | "CANCELLED" | "COMPLETED";
	eventDateId: string | null;
	startsAt: string | null;
	ticketTypeId: string | null;
	ticketTypeName: string | null;
	capacity: number;
	sold: number;
	reserved: number;
	available: number;
};

export type ReconciliationRow = {
	sale_reference: string;
	sale_status: "PENDING" | "CONFIRMED" | "ABANDONED" | "CANCELLED" | "REFUNDED";
	sale_amount: number;
	mp_payment_ref: string | null;
	mp_provider: string | null;
	mp_amount: number | null;
	siigo_invoice_name: string | null;
	siigo_invoice_status: string | null;
	siigo_cufe: string | null;
	match_status: MatchStatus;
};

export type SaleCreate = {
	buyer: {
		name: string;
		email: string;
		phone?: string;
	};
	items: Array<{
		ticketTypeId: string;
		quantity: number;
	}>;
	channel: "WEB" | "MOBILE" | "POS" | "ADMIN";
	comp: boolean;
	notes?: string;
};

export type ReportByEventRow = {
	eventId: string;
	eventName: string;
	revenue: number;
	ticketsSold: number;
	salesCount: number;
	available: number;
};

export type ReportTimeseriesRow = {
	bucket: string;
	revenue: number;
	ticketsSold: number;
	salesCount: number;
};

export type DiscountType = "PERCENT" | "FIXED";

export type Discount = {
	id: string;
	code: string;
	type: DiscountType;
	value: number;
	eventId: string | null;
	active: boolean;
	maxUses: number | null;
	uses: number;
	startsAt: string | null;
	endsAt: string | null;
	createdAt: string;
};

export type DiscountCreate = {
	code: string;
	type: DiscountType;
	value: number;
	eventId?: string | null;
	maxUses?: number | null;
	startsAt?: string | null;
	endsAt?: string | null;
};

export type DiscountUpdate = {
	active?: boolean;
	value?: number;
	maxUses?: number | null;
	startsAt?: string | null;
	endsAt?: string | null;
};

export type Webhook = {
	id: string;
	url: string;
	events: Array<string>;
	active: boolean;
	createdAt: string;
	updatedAt: string;
};

export type WebhookCreated = {
	id: string;
	url: string;
	events: Array<string>;
	active: boolean;
	createdAt: string;
	updatedAt: string;
	signingSecret: string;
};

export type WebhookCreate = {
	url: string;
	/**
	 * Subconjunto de: sale.confirmed, sale.refunded
	 */
	events: Array<"sale.confirmed" | "sale.refunded">;
	secret?: string;
};

export type Subscriber = {
	id: string;
	customerName: string | null;
	customerEmail: string;
	status: "PENDING" | "ACTIVE" | "EXPIRED" | "CANCELLED" | "PAUSED";
	startedAt: string | null;
	currentPeriodEnd: string | null;
};

export type SubscriptionCancelResult = {
	id: string;
	status: "PENDING" | "ACTIVE" | "EXPIRED" | "CANCELLED" | "PAUSED";
	cancelledAt: string | null;
};

export type SaleTicket = {
	ticketCode: string;
	ticketTypeId: string;
	ticketTypeName: string;
	quantity: number;
	seatLabel: string | null;
	checkedInAt: string | null;
};

export type CheckinResult = {
	ticketCode: string;
	checkedInAt: string | null;
	checkedInBy: string | null;
	alreadyCheckedIn: boolean;
};

export type TicketAccess = {
	ticketCode: string;
	valid: boolean;
	status: "VALID" | "USED" | "INVALID";
	saleStatus: "PENDING" | "CONFIRMED" | "ABANDONED" | "CANCELLED" | "REFUNDED";
	eventId: string;
	eventName: string;
	eventDateId: string;
	startsAt: string;
	ticketTypeName: string;
	checkedInAt: string | null;
};

export type ResendTicket = {
	ticketCode: string;
	sentTo: string;
	sentAt: string;
};

export type PostAuthDeviceCodeData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/device/code";
};

export type PostAuthDeviceCodeErrors = {
	/**
	 * Demasiadas solicitudes desde la misma IP (anti-flood).
	 */
	429: _Error;
};

export type PostAuthDeviceCodeError =
	PostAuthDeviceCodeErrors[keyof PostAuthDeviceCodeErrors];

export type PostAuthDeviceCodeResponses = {
	/**
	 * Flujo iniciado: device_code (lo poll-ea el CLI) + user_code (lo aprueba el usuario en el browser).
	 */
	200: DeviceCodeResponse;
};

export type PostAuthDeviceCodeResponse =
	PostAuthDeviceCodeResponses[keyof PostAuthDeviceCodeResponses];

export type PostAuthDeviceTokenData = {
	body: DeviceTokenRequest;
	path?: never;
	query?: never;
	url: "/auth/device/token";
};

export type PostAuthDeviceTokenErrors = {
	/**
	 * Estado RFC 8628: authorization_pending | slow_down | expired_token | access_denied | invalid_request.
	 */
	400: DeviceTokenError;
};

export type PostAuthDeviceTokenError =
	PostAuthDeviceTokenErrors[keyof PostAuthDeviceTokenErrors];

export type PostAuthDeviceTokenResponses = {
	/**
	 * Aprobado: entrega la API key ft_live_… una sola vez y consume la fila.
	 */
	200: DeviceTokenResponse;
};

export type PostAuthDeviceTokenResponse =
	PostAuthDeviceTokenResponses[keyof PostAuthDeviceTokenResponses];

export type GetMeData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/me";
};

export type GetMeErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
	/**
	 * OK
	 */
	200: {
		data: Me;
	};
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetEventsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * 1-100, default 20
		 */
		limit?: string;
		/**
		 * id del último resultado de la página previa
		 */
		cursor?: string;
	};
	url: "/events";
};

export type GetEventsErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetEventsError = GetEventsErrors[keyof GetEventsErrors];

export type GetEventsResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<Event>;
		page: Page;
	};
};

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses];

export type PostEventsData = {
	body: EventCreate;
	path?: never;
	query?: never;
	url: "/events";
};

export type PostEventsErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostEventsError = PostEventsErrors[keyof PostEventsErrors];

export type PostEventsResponses = {
	/**
	 * OK
	 */
	201: {
		data: Event;
	};
};

export type PostEventsResponse = PostEventsResponses[keyof PostEventsResponses];

export type DeleteEventsIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/events/{id}";
};

export type DeleteEventsIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type DeleteEventsIdError =
	DeleteEventsIdErrors[keyof DeleteEventsIdErrors];

export type DeleteEventsIdResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type DeleteEventsIdResponse =
	DeleteEventsIdResponses[keyof DeleteEventsIdResponses];

export type GetEventsIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/events/{id}";
};

export type GetEventsIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetEventsIdError = GetEventsIdErrors[keyof GetEventsIdErrors];

export type GetEventsIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: Event;
	};
};

export type GetEventsIdResponse =
	GetEventsIdResponses[keyof GetEventsIdResponses];

export type PatchEventsIdData = {
	body: EventUpdate;
	path: {
		id: string;
	};
	query?: never;
	url: "/events/{id}";
};

export type PatchEventsIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchEventsIdError = PatchEventsIdErrors[keyof PatchEventsIdErrors];

export type PatchEventsIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: Event;
	};
};

export type PatchEventsIdResponse =
	PatchEventsIdResponses[keyof PatchEventsIdResponses];

export type PostEventsIdPublishData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/events/{id}/publish";
};

export type PostEventsIdPublishErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostEventsIdPublishError =
	PostEventsIdPublishErrors[keyof PostEventsIdPublishErrors];

export type PostEventsIdPublishResponses = {
	/**
	 * OK
	 */
	200: {
		data: Event;
	};
};

export type PostEventsIdPublishResponse =
	PostEventsIdPublishResponses[keyof PostEventsIdPublishResponses];

export type GetEventsIdDatesData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/events/{id}/dates";
};

export type GetEventsIdDatesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetEventsIdDatesError =
	GetEventsIdDatesErrors[keyof GetEventsIdDatesErrors];

export type GetEventsIdDatesResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<EventDate>;
	};
};

export type GetEventsIdDatesResponse =
	GetEventsIdDatesResponses[keyof GetEventsIdDatesResponses];

export type PostEventsIdDatesData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/events/{id}/dates";
};

export type PostEventsIdDatesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostEventsIdDatesError =
	PostEventsIdDatesErrors[keyof PostEventsIdDatesErrors];

export type PostEventsIdDatesResponses = {
	/**
	 * OK
	 */
	201: {
		data: EventDate;
	};
};

export type PostEventsIdDatesResponse =
	PostEventsIdDatesResponses[keyof PostEventsIdDatesResponses];

export type DeleteEventsIdDatesDateIdData = {
	body?: never;
	path: {
		id: string;
		dateId: string;
	};
	query?: never;
	url: "/events/{id}/dates/{dateId}";
};

export type DeleteEventsIdDatesDateIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type DeleteEventsIdDatesDateIdError =
	DeleteEventsIdDatesDateIdErrors[keyof DeleteEventsIdDatesDateIdErrors];

export type DeleteEventsIdDatesDateIdResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type DeleteEventsIdDatesDateIdResponse =
	DeleteEventsIdDatesDateIdResponses[keyof DeleteEventsIdDatesDateIdResponses];

export type PatchEventsIdDatesDateIdData = {
	body?: never;
	path: {
		id: string;
		dateId: string;
	};
	query?: never;
	url: "/events/{id}/dates/{dateId}";
};

export type PatchEventsIdDatesDateIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchEventsIdDatesDateIdError =
	PatchEventsIdDatesDateIdErrors[keyof PatchEventsIdDatesDateIdErrors];

export type PatchEventsIdDatesDateIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: EventDate;
	};
};

export type PatchEventsIdDatesDateIdResponse =
	PatchEventsIdDatesDateIdResponses[keyof PatchEventsIdDatesDateIdResponses];

export type GetTicketTypesData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * filtra por fecha de evento
		 */
		eventDateId?: string;
		limit?: string;
		cursor?: string;
	};
	url: "/ticket-types";
};

export type GetTicketTypesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetTicketTypesError =
	GetTicketTypesErrors[keyof GetTicketTypesErrors];

export type GetTicketTypesResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<TicketType>;
		page: Page;
	};
};

export type GetTicketTypesResponse =
	GetTicketTypesResponses[keyof GetTicketTypesResponses];

export type PostTicketTypesData = {
	body: TicketTypeCreate;
	path?: never;
	query?: never;
	url: "/ticket-types";
};

export type PostTicketTypesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostTicketTypesError =
	PostTicketTypesErrors[keyof PostTicketTypesErrors];

export type PostTicketTypesResponses = {
	/**
	 * OK
	 */
	201: {
		data: TicketType;
	};
};

export type PostTicketTypesResponse =
	PostTicketTypesResponses[keyof PostTicketTypesResponses];

export type DeleteTicketTypesIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/ticket-types/{id}";
};

export type DeleteTicketTypesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type DeleteTicketTypesIdError =
	DeleteTicketTypesIdErrors[keyof DeleteTicketTypesIdErrors];

export type DeleteTicketTypesIdResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type DeleteTicketTypesIdResponse =
	DeleteTicketTypesIdResponses[keyof DeleteTicketTypesIdResponses];

export type GetTicketTypesIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/ticket-types/{id}";
};

export type GetTicketTypesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetTicketTypesIdError =
	GetTicketTypesIdErrors[keyof GetTicketTypesIdErrors];

export type GetTicketTypesIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: TicketType;
	};
};

export type GetTicketTypesIdResponse =
	GetTicketTypesIdResponses[keyof GetTicketTypesIdResponses];

export type PatchTicketTypesIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/ticket-types/{id}";
};

export type PatchTicketTypesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchTicketTypesIdError =
	PatchTicketTypesIdErrors[keyof PatchTicketTypesIdErrors];

export type PatchTicketTypesIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: TicketType;
	};
};

export type PatchTicketTypesIdResponse =
	PatchTicketTypesIdResponses[keyof PatchTicketTypesIdResponses];

export type GetSalesData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * PENDING|CONFIRMED|ABANDONED|CANCELLED|REFUNDED
		 */
		status?: string;
		/**
		 * WEB|MOBILE|POS|ADMIN
		 */
		channel?: string;
		/**
		 * id del evento
		 */
		event?: string;
		/**
		 * id de la fecha del evento
		 */
		eventDate?: string;
		/**
		 * referencia/código de la venta (parcial)
		 */
		reference?: string;
		/**
		 * nombre o email del comprador (parcial)
		 */
		buyer?: string;
		/**
		 * fecha desde (ISO 8601, sobre created_at)
		 */
		from?: string;
		/**
		 * fecha hasta (ISO 8601, sobre created_at)
		 */
		to?: string;
		limit?: string;
		cursor?: string;
	};
	url: "/sales";
};

export type GetSalesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetSalesError = GetSalesErrors[keyof GetSalesErrors];

export type GetSalesResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<Sale>;
		page: Page;
	};
};

export type GetSalesResponse = GetSalesResponses[keyof GetSalesResponses];

export type PostSalesData = {
	body: SaleCreate;
	path?: never;
	query?: never;
	url: "/sales";
};

export type PostSalesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostSalesError = PostSalesErrors[keyof PostSalesErrors];

export type PostSalesResponses = {
	/**
	 * OK
	 */
	201: {
		data: SaleDetail;
	};
};

export type PostSalesResponse = PostSalesResponses[keyof PostSalesResponses];

export type GetSalesIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/sales/{id}";
};

export type GetSalesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetSalesIdError = GetSalesIdErrors[keyof GetSalesIdErrors];

export type GetSalesIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: SaleDetail;
	};
};

export type GetSalesIdResponse = GetSalesIdResponses[keyof GetSalesIdResponses];

export type PostSalesIdCancelData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/sales/{id}/cancel";
};

export type PostSalesIdCancelErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostSalesIdCancelError =
	PostSalesIdCancelErrors[keyof PostSalesIdCancelErrors];

export type PostSalesIdCancelResponses = {
	/**
	 * OK
	 */
	200: {
		data: Sale;
	};
};

export type PostSalesIdCancelResponse =
	PostSalesIdCancelResponses[keyof PostSalesIdCancelResponses];

export type PostSalesIdRefundData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/sales/{id}/refund";
};

export type PostSalesIdRefundErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostSalesIdRefundError =
	PostSalesIdRefundErrors[keyof PostSalesIdRefundErrors];

export type PostSalesIdRefundResponses = {
	/**
	 * OK
	 */
	200: {
		data: Sale;
	};
};

export type PostSalesIdRefundResponse =
	PostSalesIdRefundResponses[keyof PostSalesIdRefundResponses];

export type GetMembershipPlansData = {
	body?: never;
	path?: never;
	query?: {
		limit?: string;
		cursor?: string;
	};
	url: "/membership-plans";
};

export type GetMembershipPlansErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetMembershipPlansError =
	GetMembershipPlansErrors[keyof GetMembershipPlansErrors];

export type GetMembershipPlansResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<MembershipPlan>;
		page: Page;
	};
};

export type GetMembershipPlansResponse =
	GetMembershipPlansResponses[keyof GetMembershipPlansResponses];

export type PostMembershipPlansData = {
	body: MembershipPlanCreate;
	path?: never;
	query?: never;
	url: "/membership-plans";
};

export type PostMembershipPlansErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostMembershipPlansError =
	PostMembershipPlansErrors[keyof PostMembershipPlansErrors];

export type PostMembershipPlansResponses = {
	/**
	 * OK
	 */
	201: {
		data: MembershipPlan;
	};
};

export type PostMembershipPlansResponse =
	PostMembershipPlansResponses[keyof PostMembershipPlansResponses];

export type DeleteMembershipPlansIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/membership-plans/{id}";
};

export type DeleteMembershipPlansIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type DeleteMembershipPlansIdError =
	DeleteMembershipPlansIdErrors[keyof DeleteMembershipPlansIdErrors];

export type DeleteMembershipPlansIdResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type DeleteMembershipPlansIdResponse =
	DeleteMembershipPlansIdResponses[keyof DeleteMembershipPlansIdResponses];

export type GetMembershipPlansIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/membership-plans/{id}";
};

export type GetMembershipPlansIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetMembershipPlansIdError =
	GetMembershipPlansIdErrors[keyof GetMembershipPlansIdErrors];

export type GetMembershipPlansIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: MembershipPlan;
	};
};

export type GetMembershipPlansIdResponse =
	GetMembershipPlansIdResponses[keyof GetMembershipPlansIdResponses];

export type PatchMembershipPlansIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/membership-plans/{id}";
};

export type PatchMembershipPlansIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchMembershipPlansIdError =
	PatchMembershipPlansIdErrors[keyof PatchMembershipPlansIdErrors];

export type PatchMembershipPlansIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: MembershipPlan;
	};
};

export type PatchMembershipPlansIdResponse =
	PatchMembershipPlansIdResponses[keyof PatchMembershipPlansIdResponses];

export type GetVenuesData = {
	body?: never;
	path?: never;
	query?: {
		limit?: string;
		cursor?: string;
	};
	url: "/venues";
};

export type GetVenuesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetVenuesError = GetVenuesErrors[keyof GetVenuesErrors];

export type GetVenuesResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<Venue>;
		page: Page;
	};
};

export type GetVenuesResponse = GetVenuesResponses[keyof GetVenuesResponses];

export type PostVenuesData = {
	body: VenueCreate;
	path?: never;
	query?: never;
	url: "/venues";
};

export type PostVenuesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostVenuesError = PostVenuesErrors[keyof PostVenuesErrors];

export type PostVenuesResponses = {
	/**
	 * OK
	 */
	201: {
		data: Venue;
	};
};

export type PostVenuesResponse = PostVenuesResponses[keyof PostVenuesResponses];

export type DeleteVenuesIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/venues/{id}";
};

export type DeleteVenuesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type DeleteVenuesIdError =
	DeleteVenuesIdErrors[keyof DeleteVenuesIdErrors];

export type DeleteVenuesIdResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type DeleteVenuesIdResponse =
	DeleteVenuesIdResponses[keyof DeleteVenuesIdResponses];

export type GetVenuesIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/venues/{id}";
};

export type GetVenuesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetVenuesIdError = GetVenuesIdErrors[keyof GetVenuesIdErrors];

export type GetVenuesIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: Venue;
	};
};

export type GetVenuesIdResponse =
	GetVenuesIdResponses[keyof GetVenuesIdResponses];

export type PatchVenuesIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/venues/{id}";
};

export type PatchVenuesIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchVenuesIdError = PatchVenuesIdErrors[keyof PatchVenuesIdErrors];

export type PatchVenuesIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: Venue;
	};
};

export type PatchVenuesIdResponse =
	PatchVenuesIdResponses[keyof PatchVenuesIdResponses];

export type GetStaffData = {
	body?: never;
	path?: never;
	query?: {
		limit?: string;
		cursor?: string;
	};
	url: "/staff";
};

export type GetStaffErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetStaffError = GetStaffErrors[keyof GetStaffErrors];

export type GetStaffResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<StaffUser>;
		page: Page;
	};
};

export type GetStaffResponse = GetStaffResponses[keyof GetStaffResponses];

export type PostStaffData = {
	body: StaffCreate;
	path?: never;
	query?: never;
	url: "/staff";
};

export type PostStaffErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostStaffError = PostStaffErrors[keyof PostStaffErrors];

export type PostStaffResponses = {
	/**
	 * OK
	 */
	201: {
		data: StaffUser;
	};
};

export type PostStaffResponse = PostStaffResponses[keyof PostStaffResponses];

export type PatchStaffIdRoleData = {
	body: RoleUpdate;
	path: {
		id: string;
	};
	query?: never;
	url: "/staff/{id}/role";
};

export type PatchStaffIdRoleErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchStaffIdRoleError =
	PatchStaffIdRoleErrors[keyof PatchStaffIdRoleErrors];

export type PatchStaffIdRoleResponses = {
	/**
	 * OK
	 */
	200: {
		data: StaffUser;
	};
};

export type PatchStaffIdRoleResponse =
	PatchStaffIdRoleResponses[keyof PatchStaffIdRoleResponses];

export type GetReportsSummaryData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * 7d | 30d (default) | 90d | 1y
		 */
		period?: string;
	};
	url: "/reports/summary";
};

export type GetReportsSummaryErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsSummaryError =
	GetReportsSummaryErrors[keyof GetReportsSummaryErrors];

export type GetReportsSummaryResponses = {
	/**
	 * OK
	 */
	200: {
		data: ReportSummary;
	};
};

export type GetReportsSummaryResponse =
	GetReportsSummaryResponses[keyof GetReportsSummaryResponses];

export type GetReportsInventoryData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Filtra por evento
		 */
		eventId?: string;
		/**
		 * Filtra por fecha del evento
		 */
		eventDateId?: string;
		/**
		 * Inicio de función ≥ (ISO 8601)
		 */
		from?: string;
		/**
		 * Inicio de función ≤ (ISO 8601)
		 */
		to?: string;
		/**
		 * Incluir eventos/fechas en DRAFT (default false)
		 */
		includeDrafts?: string;
		/**
		 * event | date | ticketType (default)
		 */
		groupBy?: string;
	};
	url: "/reports/inventory";
};

export type GetReportsInventoryErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsInventoryError =
	GetReportsInventoryErrors[keyof GetReportsInventoryErrors];

export type GetReportsInventoryResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<InventoryRow>;
	};
};

export type GetReportsInventoryResponse =
	GetReportsInventoryResponses[keyof GetReportsInventoryResponses];

export type GetReportsReconciliationData = {
	body?: never;
	path?: never;
	query: {
		/**
		 * ISO 8601 (inicio, sobre Sale.created_at)
		 */
		date_from: string;
		/**
		 * ISO 8601 (fin)
		 */
		date_to: string;
		/**
		 * Filtra por flag: OK|MISSING_INVOICE|MISSING_CUFE|AMOUNT_MISMATCH|MISSING_PAYMENT
		 */
		match_status?: string;
		/**
		 * Filtra por payment_provider (ej: mercadopago)
		 */
		provider?: string;
		/**
		 * Página 1-based (default 1)
		 */
		page?: string;
		/**
		 * Tamaño de página 1..500 (default 100)
		 */
		page_size?: string;
	};
	url: "/reports/reconciliation";
};

export type GetReportsReconciliationErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsReconciliationError =
	GetReportsReconciliationErrors[keyof GetReportsReconciliationErrors];

export type GetReportsReconciliationResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<ReconciliationRow>;
	};
};

export type GetReportsReconciliationResponse =
	GetReportsReconciliationResponses[keyof GetReportsReconciliationResponses];

export type GetReportsExportsReconciliationData = {
	body?: never;
	path?: never;
	query: {
		/**
		 * ISO 8601 (inicio, sobre Sale.created_at)
		 */
		date_from: string;
		/**
		 * ISO 8601 (fin)
		 */
		date_to: string;
		/**
		 * Filtra por flag: OK|MISSING_INVOICE|MISSING_CUFE|AMOUNT_MISMATCH|MISSING_PAYMENT
		 */
		match_status?: string;
		/**
		 * Filtra por payment_provider (ej: mercadopago)
		 */
		provider?: string;
	};
	url: "/reports/exports/reconciliation";
};

export type GetReportsExportsReconciliationErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsExportsReconciliationError =
	GetReportsExportsReconciliationErrors[keyof GetReportsExportsReconciliationErrors];

export type GetReportsExportsReconciliationResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type GetReportsExportsReconciliationResponse =
	GetReportsExportsReconciliationResponses[keyof GetReportsExportsReconciliationResponses];

export type GetReportsExportsAttendeesData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Filtra por Event.id
		 */
		event?: string;
		/**
		 * Filtra por EventDate.id
		 */
		eventDate?: string;
		/**
		 * ISO 8601 — desde (sobre Sale.created_at)
		 */
		from?: string;
		/**
		 * ISO 8601 — hasta (sobre Sale.created_at)
		 */
		to?: string;
		/**
		 * PENDING|CONFIRMED|ABANDONED|CANCELLED|REFUNDED (default CONFIRMED)
		 */
		status?: string;
	};
	url: "/reports/exports/attendees";
};

export type GetReportsExportsAttendeesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsExportsAttendeesError =
	GetReportsExportsAttendeesErrors[keyof GetReportsExportsAttendeesErrors];

export type GetReportsExportsAttendeesResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type GetReportsExportsAttendeesResponse =
	GetReportsExportsAttendeesResponses[keyof GetReportsExportsAttendeesResponses];

export type GetReportsExportsBuyersData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Filtra por Event.id
		 */
		event?: string;
		/**
		 * Filtra por EventDate.id
		 */
		eventDate?: string;
		/**
		 * ISO 8601 — desde (sobre Sale.created_at)
		 */
		from?: string;
		/**
		 * ISO 8601 — hasta (sobre Sale.created_at)
		 */
		to?: string;
		/**
		 * PENDING|CONFIRMED|ABANDONED|CANCELLED|REFUNDED (default CONFIRMED)
		 */
		status?: string;
	};
	url: "/reports/exports/buyers";
};

export type GetReportsExportsBuyersErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsExportsBuyersError =
	GetReportsExportsBuyersErrors[keyof GetReportsExportsBuyersErrors];

export type GetReportsExportsBuyersResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type GetReportsExportsBuyersResponse =
	GetReportsExportsBuyersResponses[keyof GetReportsExportsBuyersResponses];

export type GetReportsExportsSubscribersData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/reports/exports/subscribers";
};

export type GetReportsExportsSubscribersErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsExportsSubscribersError =
	GetReportsExportsSubscribersErrors[keyof GetReportsExportsSubscribersErrors];

export type GetReportsExportsSubscribersResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type GetReportsExportsSubscribersResponse =
	GetReportsExportsSubscribersResponses[keyof GetReportsExportsSubscribersResponses];

export type GetReportsByEventData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * ISO 8601, filtra Sale.created_at (gte)
		 */
		from?: string;
		/**
		 * ISO 8601, filtra Sale.created_at (lte)
		 */
		to?: string;
		/**
		 * PENDING|CONFIRMED (default)|ABANDONED|CANCELLED|REFUNDED
		 */
		status?: string;
	};
	url: "/reports/by-event";
};

export type GetReportsByEventErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsByEventError =
	GetReportsByEventErrors[keyof GetReportsByEventErrors];

export type GetReportsByEventResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<ReportByEventRow>;
	};
};

export type GetReportsByEventResponse =
	GetReportsByEventResponses[keyof GetReportsByEventResponses];

export type GetReportsTimeseriesData = {
	body?: never;
	path?: never;
	query: {
		/**
		 * day | week | month
		 */
		interval: string;
		/**
		 * ISO 8601, filtra Sale.created_at (gte)
		 */
		from?: string;
		/**
		 * ISO 8601, filtra Sale.created_at (lte)
		 */
		to?: string;
		/**
		 * ID de evento del workspace (opcional)
		 */
		event?: string;
	};
	url: "/reports/timeseries";
};

export type GetReportsTimeseriesErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetReportsTimeseriesError =
	GetReportsTimeseriesErrors[keyof GetReportsTimeseriesErrors];

export type GetReportsTimeseriesResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<ReportTimeseriesRow>;
	};
};

export type GetReportsTimeseriesResponse =
	GetReportsTimeseriesResponses[keyof GetReportsTimeseriesResponses];

export type GetDiscountsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * id de evento para filtrar
		 */
		event?: string;
		/**
		 * true|false
		 */
		active?: string;
		limit?: string;
		cursor?: string;
	};
	url: "/discounts";
};

export type GetDiscountsErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetDiscountsError = GetDiscountsErrors[keyof GetDiscountsErrors];

export type GetDiscountsResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<Discount>;
		page: Page;
	};
};

export type GetDiscountsResponse =
	GetDiscountsResponses[keyof GetDiscountsResponses];

export type PostDiscountsData = {
	body: DiscountCreate;
	path?: never;
	query?: never;
	url: "/discounts";
};

export type PostDiscountsErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostDiscountsError = PostDiscountsErrors[keyof PostDiscountsErrors];

export type PostDiscountsResponses = {
	/**
	 * OK
	 */
	201: {
		data: Discount;
	};
};

export type PostDiscountsResponse =
	PostDiscountsResponses[keyof PostDiscountsResponses];

export type DeleteDiscountsIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/discounts/{id}";
};

export type DeleteDiscountsIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type DeleteDiscountsIdError =
	DeleteDiscountsIdErrors[keyof DeleteDiscountsIdErrors];

export type DeleteDiscountsIdResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type DeleteDiscountsIdResponse =
	DeleteDiscountsIdResponses[keyof DeleteDiscountsIdResponses];

export type PatchDiscountsIdData = {
	body: DiscountUpdate;
	path: {
		id: string;
	};
	query?: never;
	url: "/discounts/{id}";
};

export type PatchDiscountsIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PatchDiscountsIdError =
	PatchDiscountsIdErrors[keyof PatchDiscountsIdErrors];

export type PatchDiscountsIdResponses = {
	/**
	 * OK
	 */
	200: {
		data: Discount;
	};
};

export type PatchDiscountsIdResponse =
	PatchDiscountsIdResponses[keyof PatchDiscountsIdResponses];

export type GetWebhooksData = {
	body?: never;
	path?: never;
	query?: {
		limit?: string;
		cursor?: string;
	};
	url: "/webhooks";
};

export type GetWebhooksErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetWebhooksError = GetWebhooksErrors[keyof GetWebhooksErrors];

export type GetWebhooksResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<Webhook>;
		page: Page;
	};
};

export type GetWebhooksResponse =
	GetWebhooksResponses[keyof GetWebhooksResponses];

export type PostWebhooksData = {
	body: WebhookCreate;
	path?: never;
	query?: never;
	url: "/webhooks";
};

export type PostWebhooksErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostWebhooksError = PostWebhooksErrors[keyof PostWebhooksErrors];

export type PostWebhooksResponses = {
	/**
	 * OK
	 */
	201: {
		data: WebhookCreated;
	};
};

export type PostWebhooksResponse =
	PostWebhooksResponses[keyof PostWebhooksResponses];

export type DeleteWebhooksIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/webhooks/{id}";
};

export type DeleteWebhooksIdErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type DeleteWebhooksIdError =
	DeleteWebhooksIdErrors[keyof DeleteWebhooksIdErrors];

export type DeleteWebhooksIdResponses = {
	/**
	 * OK
	 */
	200: {
		[key: string]: unknown;
	};
};

export type DeleteWebhooksIdResponse =
	DeleteWebhooksIdResponses[keyof DeleteWebhooksIdResponses];

export type GetMembershipPlansIdSubscribersData = {
	body?: never;
	path: {
		id: string;
	};
	query?: {
		/**
		 * PENDING|ACTIVE|EXPIRED|CANCELLED|PAUSED
		 */
		status?: string;
		limit?: string;
		cursor?: string;
	};
	url: "/membership-plans/{id}/subscribers";
};

export type GetMembershipPlansIdSubscribersErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetMembershipPlansIdSubscribersError =
	GetMembershipPlansIdSubscribersErrors[keyof GetMembershipPlansIdSubscribersErrors];

export type GetMembershipPlansIdSubscribersResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<Subscriber>;
		page: Page;
	};
};

export type GetMembershipPlansIdSubscribersResponse =
	GetMembershipPlansIdSubscribersResponses[keyof GetMembershipPlansIdSubscribersResponses];

export type PostSubscriptionsIdCancelData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/subscriptions/{id}/cancel";
};

export type PostSubscriptionsIdCancelErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostSubscriptionsIdCancelError =
	PostSubscriptionsIdCancelErrors[keyof PostSubscriptionsIdCancelErrors];

export type PostSubscriptionsIdCancelResponses = {
	/**
	 * OK
	 */
	200: {
		data: SubscriptionCancelResult;
	};
};

export type PostSubscriptionsIdCancelResponse =
	PostSubscriptionsIdCancelResponses[keyof PostSubscriptionsIdCancelResponses];

export type GetSalesIdTicketsData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/sales/{id}/tickets";
};

export type GetSalesIdTicketsErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetSalesIdTicketsError =
	GetSalesIdTicketsErrors[keyof GetSalesIdTicketsErrors];

export type GetSalesIdTicketsResponses = {
	/**
	 * OK
	 */
	200: {
		data: Array<SaleTicket>;
	};
};

export type GetSalesIdTicketsResponse =
	GetSalesIdTicketsResponses[keyof GetSalesIdTicketsResponses];

export type PostTicketsTicketCodeCheckinData = {
	body?: never;
	path: {
		ticketCode: string;
	};
	query?: never;
	url: "/tickets/{ticketCode}/checkin";
};

export type PostTicketsTicketCodeCheckinErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostTicketsTicketCodeCheckinError =
	PostTicketsTicketCodeCheckinErrors[keyof PostTicketsTicketCodeCheckinErrors];

export type PostTicketsTicketCodeCheckinResponses = {
	/**
	 * OK
	 */
	200: {
		data: CheckinResult;
	};
};

export type PostTicketsTicketCodeCheckinResponse =
	PostTicketsTicketCodeCheckinResponses[keyof PostTicketsTicketCodeCheckinResponses];

export type GetTicketsTicketCodeAccessData = {
	body?: never;
	path: {
		ticketCode: string;
	};
	query?: never;
	url: "/tickets/{ticketCode}/access";
};

export type GetTicketsTicketCodeAccessErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type GetTicketsTicketCodeAccessError =
	GetTicketsTicketCodeAccessErrors[keyof GetTicketsTicketCodeAccessErrors];

export type GetTicketsTicketCodeAccessResponses = {
	/**
	 * OK
	 */
	200: {
		data: TicketAccess;
	};
};

export type GetTicketsTicketCodeAccessResponse =
	GetTicketsTicketCodeAccessResponses[keyof GetTicketsTicketCodeAccessResponses];

export type PostTicketsTicketCodeResendData = {
	body?: never;
	path: {
		ticketCode: string;
	};
	query?: never;
	url: "/tickets/{ticketCode}/resend";
};

export type PostTicketsTicketCodeResendErrors = {
	/**
	 * Credencial inválida o ausente.
	 */
	401: _Error;
	/**
	 * Rol insuficiente o recurso no accesible.
	 */
	403: _Error;
	/**
	 * Recurso inexistente o fuera de alcance.
	 */
	404: _Error;
	/**
	 * Validación del cuerpo/parámetros.
	 */
	422: _Error;
};

export type PostTicketsTicketCodeResendError =
	PostTicketsTicketCodeResendErrors[keyof PostTicketsTicketCodeResendErrors];

export type PostTicketsTicketCodeResendResponses = {
	/**
	 * OK
	 */
	200: {
		data: ResendTicket;
	};
};

export type PostTicketsTicketCodeResendResponse =
	PostTicketsTicketCodeResendResponses[keyof PostTicketsTicketCodeResendResponses];

export type ClientOptions = {
	baseUrl: "http://localhost:3000/api/v1" | (string & {});
};
